### ISSUE TITLE
ResourceNotFoundException when inflating view

### ISSUE THREAD

**Issue by asepnopan** [keymapperorg/KeyMapper#1009]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] squash and merge
- [x] delete branch

**Discord message link/email recipient**
"Phoenixhunt045@gmail.com"
**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**

**Screenshots**
![IMG_20220521_235049](https://user-images.githubusercontent.com/55190897/169661607-2846b726-01c1-4e34-bad0-036ed57d62f9.jpg)
![IMG_20220521_235105](https://user-images.githubusercontent.com/55190897/169661625-c4aefc04-5413-4fa5-b751-d535ef34e422.jpg)

**Smartphone (please complete the following information):**
 - Device: [Advan S5E Full View ]
 - Android version: [Android 7.0]

**Additional context**
Add any other context about the problem here. The app is always automatic stop

**Comment by asepnopan** [comment]
I just want to play minecraft, using generic usb joystick without root 
Here are the keymapper https://drive.google.com/drive/folders/13qdQ0e8Lw7zfuj0So6sb5jnCDHz1mMHT

**Comment by sds100** [comment]
Hi, thank you for the bug report! It should possible to fix. Can you install this apk https://github.com/keymapperorg/KeyMapper/releases/download/v2.4.0/keymapper-v2.4.0-debug.apk and see if it crashes. If it also crashes then send me a bug report from that apk.

**Comment by asepnopan** [comment]
![IMG_20220522_094918](https://user-images.githubusercontent.com/55190897/169676705-d0e7ec08-c180-4928-a145-cf2ea6516a47.jpg)
[key_mapper_report_20220521-230615.zip](https://github.com/keymapperorg/KeyMapper/files/8748687/key_mapper_report_20220521-230615.zip)
When i press pen button the app is always crashes.

**Comment by sds100** [comment]
fixed. Thank you for the bug report!
