### ISSUE TITLE
go to previous app, nukes recent apps view

### ISSUE THREAD

**Issue by JanJenicek** [keymapperorg/KeyMapper#1010]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
I'm running official LineageOS 19.1 + Magisk. When I set any key event to trigger "go to previous app" (sorry not sure exact phrase, using non English localization) and there is none in recents screen, the recents screen view is completely unreachable until device is restarted.

I expect this to be more ROM related, but I would like to know if more people had this issue. Or just simply document this behavior here.

**To Reproduce**
Set any trigger to action "go to previous app".

**Expected behavior**
No action should be taken, when there is no app to go to.

**Screenshots**
Not possible recents screen will not show.

**Smartphone (please complete the following information):**
 - Device: [S10e]
 - Android version: [Android 12][LineageOS 19.1]

**Additional context**

**Comment by GL513** [comment]
Can you send a screen recording and a Bug Report from Keymapper?
Both would help a lot, thanks.

**Comment by JanJenicek** [comment]
Sorry for late response. I struggled with my phone for last two days. Resulting in non-related factory reset.

Now I'm unable to reproduce the issue. My guess, your app was first victim of some other issue.

Unfortunately I just start using your app at that time and described behavior was there from day 1 and was consistent for several days.

**Comment by JanJenicek** [comment]
Factory reset helped.

**Comment by GL513** [comment]
> Sorry for late response. I struggled with my phone for last two days. Resulting in non-related factory reset.
> 
> Now I'm unable to reproduce the issue. My guess, your app was first victim of some other issue.
> 
> Unfortunately I just start using your app at that time and described behavior was there from day 1 and was consistent for several days.

Thank you for contruibuting! If you suspect any other unusual behavior, let us know please :)
