### ISSUE TITLE
Don't show Do Not Disturb permission prompt on devices that don't have the settings

### ISSUE THREAD

**Issue by medanisjbara** [keymapperorg/KeyMapper#1016]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] Doesn't seem to be an API to detect that a feature doesn't support it so just show a "never show again" button in the dialog. The AOSP Settings app seems to check [this](https://cs.android.com/android/platform/superproject/+/master:packages/apps/Settings/src/com/android/settings/notification/zen/ZenAccessSettings.java;drc=4c7981eb0d2b0f8b6fd1b96c5fee055caa0336d8;l=99). This doesn't work because you need MANAGE_USERS permission and its only for system apps.
- [x] test on TV #281 
- [x] squash and merge
- [x] delete branch

**Describe the bug**
It seems like "Do Not Distrub access" is not available on Android Go (the same way "Display over other apps" (system alert window) isn't.
This results in
* `Key Mapper requireés permission to modify the Do Not Disturb mode if you want the button to work as expected in Do Not Disturb mode!` error to show on top right after a trigger is recorded (when creating a keymap, screenshot 1). The fix button besides it does nothing on Android Go (screenshot 2) which looks really similar to "Display over other apps" on Android Go 10 (screenshot 3)
* `This trigger will not work as expected in Do Not Disturb mode!` warning in every keymap created. (screenshot 4). 
I tested out a couple of functions in Do Not Disturb mode and they seem to work (which suggests that the warning and the error can be ignored).

**To Reproduce**
Install the app on Android Go 10 And create a keymap for one of the volume button (And possibly other buttons).

**Expected behavior**
Possible solutions can be:
* A toast that tells you that "Do not disturb access doesn't work on your device" if the app detects Android Go. (And the error and the warning will not be shown again).
* A `dismiss` button that will dismiss the unfixable error (under the `fix` button) which in it's turn dismiss all future warnings (Since the user cannot do anything to fix this).

**Screenshots**
* Screenshot 1:
![Screenshot_1](https://user-images.githubusercontent.com/74317212/170492969-19102846-7f41-47be-97b2-0a9a107f6079.png)
* Screenshot 2:
![Screenshot_2](https://user-images.githubusercontent.com/74317212/170493240-14f9b37f-d252-434c-9611-1e99c269e0a9.png)
* Screenshot 3:
![Screenshot_3](https://user-images.githubusercontent.com/74317212/170493328-54d1de94-576a-42ff-9911-60005a253caa.png)
* Screenshot 4:
![Screenshot_4](https://user-images.githubusercontent.com/74317212/170493378-fe23f62c-4dd7-4d17-8f7c-18069ef91b05.png)

**Smartphone:**
 - Device: [Logicom Le Spark](https://www.logicom-europe.com/fr/gamme-4g2/761-le-spark.html)
 - Android version: Android 10 Go

**Comment by sds100** [comment]
Thank you for this! I've seen this many times before but never have been sure why on certain devices it came up!

**Comment by sds100** [comment]
implemented
