### ISSUE TITLE
Adding a french translation

### ISSUE THREAD

**Issue by iliasmc** [keymapperorg/KeyMapper#1018]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Comment by jambl3r** [comment]
French translation is provided via Crowdin and is currently 13% complete.
https://crowdin.com/project/key-mapper/fr
Feel free to contribute here if you like.
Thanks for your interest.
