### ISSUE TITLE
Can't have multiple taps using my Bluetooth keyboard..

### ISSUE THREAD

**Issue by SkywarsZYT** [keymapperorg/KeyMapper#1022]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

Email me: skywarszm@gmail.com

Bug:
You can't have multiple taps at the same time. I wanted to keymap my physical keyboard buttons to tap uncertain areas, so I could play my games. But it turns out you can't tap at multiple locations at the same time.

Steps to reproduce the behavior: *You need a physical keyboard for this to work properly*
Set up two or more keyboard keys to tap in different areas which can be triggered. Then press this two keyboard keys at the same time, and they won't tap the places at the same time.

**Expected behavior**

 - Device: Infinix Note 5 Stylus
                  4/64GB
 - Android version: Android 10
 - My Keyboard: HP TouchPad Wireless Bluetooth Keyboard

**Comment by sds100** [comment]
Hi, this isn't an issue with your set up but is a restriction in Android. It doesn't allow accessibility services to tap multiple places at once on the screen. This is the only method of doing this so there is nothing we can do to fix this :). I will add this to the known issues page on the website
