### ISSUE TITLE
Support Android 12L

### ISSUE THREAD

**Issue by sds100** [keymapperorg/KeyMapper#1025]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] update documentation
- [x] #1031 
- [x] fix crash when changing device format when on home screen
- [x] squash and merge
- [x] delete branch

**Comment by GL513** [comment]
13 is just around the corner... Let's hope those VMs are working like they should. Have their been any related issues with 13 yet?

**Comment by sds100** [comment]
VMs? I haven't looked at 13 yet 😄. I usually wait until after it it has been released to stable to start working on it.

**Comment by sds100** [comment]
If you are able to get an emulator set up in Android Studio then you can test ;)
