### ISSUE TITLE
Button Mapper Script missing

### ISSUE THREAD

**Issue by vathzen** [keymapperorg/KeyMapper#1030]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
Not able to run manual command on Android12 in both windows and Unix

**To Reproduce**
Connect device to Linux/Windows system
run adb devices ( device is shown )
run "adb shell sh /sdcard/Android/data/flar2.homebutton/logcat.sh" to enable remapping of Google Assistant button on Android 12 ( as given in https://setup.buttonmapper.app )
logcat.sh is not found

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**
Before running this command Button Mapper is Unable to detect the google assistant button.
After running this command Button Mapper should technically be able to detect

**Screenshots**
![image](https://user-images.githubusercontent.com/16957582/172314047-810c1b61-dbdc-4d84-81ae-440bb50997ac.png)

**Smartphone (please complete the following information):**
 - Device: Moto Edge 20 Pro
 - Android version: Android 12

**Additional context**
Not able to run the script given for older versions also.
![image](https://user-images.githubusercontent.com/16957582/172314360-767ad763-80a5-4354-818d-6a5a30d482a2.png)

**Comment by sds100** [comment]
Hi, this is an issue with a different app. Button Mapper https://play.google.com/store/search?q=button+mapper&c=apps and not Key Mapper 😉
