### ISSUE TITLE
Extra logging crashes

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#1032]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

https://discord.com/channels/717499872219103263/717500546910650488/981113436337471488

**Describe the bug**

Extra logging crashes keymapper

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

https://cdn.discordapp.com/attachments/717500546910650488/981113436144549928/key_mapper_report_20220531-113242.zip

**Expected behavior**

KeyMapper doesnt crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

Manufacturer: tissot
Device: Xiaomi Model: Mi A1
Android SDK version: 28

**Additional context**

4gb RAM
Usually not under heavy use

**Comment by sds100** [comment]
Don't know how to reproduce 🤷‍♂️
