### ISSUE TITLE
Action to toggle/mute/unmute a specific volume stream

### ISSUE THREAD

**Issue by sds100** [keymapperorg/KeyMapper#1039]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] update documentation
- [x] merge and delete branch (don't squash because want commit history to see why I made changes)
- [x] notify email by Bernadi at 09/06/22

**Comment by GL513** [comment]
See #991

**Comment by sds100** [comment]
implemented

**Comment by sds100** [comment]
Fix volume increase actions become decrease actions.

**Comment by sds100** [comment]
fixed
