### ISSUE TITLE
Adding "app not playing media" constraint is saved as "app playing media"

### ISSUE THREAD

**Issue by Berkwe** [keymapperorg/KeyMapper#1047]
ENGLİSH (GOOGLE TRANSLATE)

**Developer TODOs (do not uninstall)**
- [ ] create new branch. put the problem number at the beginning of the name unless it's a very quick fix.
- Write [ ] tests. write the topic number in the comment
- [ ] update documentation
- Merge [ ] branch and delete (don't squash because I want to commit history to see why I made changes)

**E-mail: durgunberke64@gmail.com**

** "app not playing media" in Constraint does not work**
A clear and concise explanation of what the error is.

** 1. Add a constraint as "app not playing media"

2. Save the work

3. The work you added appears as "app playing media" **
Steps to reproduce the behavior.

Upload a backup of your keymaps. [
[keymapper_mappings.zip](https://github.com/keymapperorg/KeyMapper/files/8946507/keymapper_mappings.zip)
](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

** add a constraint as "app not playing media" **
Here is a clear and concise explanation of what you expect to happen:

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Smartphone (please fill in the information below):**
 - Device: [general mobile gm 9 pro]
 - Android version: [android 9.0 pie]

**Additional context**
Add any other context related to the issue here.

MY LANGUAGE (TURKİSH)

**Geliştirici YAPILACAKLARI (kaldırmayın)**
- [ ] yeni dal oluştur. çok hızlı bir düzeltme değilse, sorun numarasını adın başına koyun.
- [ ] testler yaz. konu numarasını yoruma yaz
- [ ] belgeleri güncelle
- [ ] dalı birleştir ve sil (ezmeyin çünkü neden değişiklik yaptığımı görmek için geçmişi işlemek istiyorum)

**E-posta: durgunberke64@gmail.com**

**Constraint içindeki "app not playing media" çalışmıyor**
Hatanın ne olduğuna dair net ve özlü bir açıklama.

** 1. "App not playing media" olarak bir constraint ekleyin

2. Çalışmayı kaydedin 

3. Eklediğiniz çalışma "app playing media" olarak görünüyor **
Davranışı yeniden oluşturma adımları.

Anahtar haritalarınızın bir yedeğini yükleyin. [
[keymapper_mappings.zip](https://github.com/keymapperorg/KeyMapper/files/8946515/keymapper_mappings.zip)
](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

** "App not playing media" olarak bir constraint eklemek **
Ne olmasını beklediğinizin açık ve özlü bir açıklaması:

**Ekran görüntüleri**
Varsa, sorununuzu açıklamaya yardımcı olması için ekran görüntüleri ekleyin.

**Akıllı telefon (lütfen aşağıdaki bilgileri doldurun):**
 - Cihaz: [general mobile gm 9 pro]
 - Android sürümü: [android 9.0 pie]

**Ek bağlam**
Sorunla ilgili başka bağlamları buraya ekleyin.

**Comment by sds100** [comment]
Fixed
