### ISSUE TITLE
Question: hold key A and simultaneously double press key B - how to do achieve such mapping

### ISSUE THREAD

**Issue by dumblob** [keymapperorg/KeyMapper#1061]
Recently I wanted to create the mapping described in the title. But I was unable to do it in the app. Does KeyMapper support such mappings? If so, may I somehow achieve it through GUI or at least by editing some config file?

This is a low-priority for me, so do not waste your time with details - I just need a kick in the right direction.

Thanks everyone!

**Comment by sds100** [comment]
I haven't explicitly added a way to make a trigger like this but may be someone creative can think of a crazy way to make it work. 😂 There are so many combinations of things you can try. I guess if I add #711 then it would be possible.
