### ISSUE TITLE
Ability to use features with the screen off

### ISSUE THREAD

**Issue by Berkwe** [keymapperorg/KeyMapper#1071]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)
_________________________________________________________
this is just a small request. although I gave root permission, key mapper does not work when the screen is off, I would appreciate it if you could fix it.

**Comment by sds100** [comment]
Hi, which trigger are you using?

**Comment by NeatNit** [comment]
> this is just a small request. although I gave root permission, key mapper does not work when the screen is off, I would appreciate it if you could fix it.

Did you enable this option in your key map?

![Screenshot_20220715-144214_Key Mapper](https://user-images.githubusercontent.com/2400026/179216646-a9ebf81f-f5f6-4ab7-9013-b7f2540ea38c.jpg)

**Comment by spitfire94** [comment]
This should be marked as a bug. Recently needed to reflash my device. Had screen off actions working before, but no longer. Will investigate further another time.

**Comment by spitfire94** [comment]
Turned out to be a visual glitch with Magisk. KeyMapper appeared approved in the UI, but the logs showed it was being revoked. Entirely removing KeyMapper from superuser apps, then re-approving fixed the problem.

**Comment by spitfire94** [comment]
Maybe have 'Detect triggers when screen is off' be a global option. Already have constraints for screen and lock states. As a per action option, it's a bit confusing to new users, and repetitive to widely enable.

**Comment by sds100** [comment]
I think it is better to have it per key map rather than global. To switch it now to global would also break people's setups so I think I'll just leave it as is. This setting is barely used and very few people have loads of key maps that they want to work when the screen is off - usually it is only the volume buttons.

**Comment by sds100** [comment]
@Berkwe Is this still not working for you? If you still need help please ask in the Help thread in Discussions or on Discord.
