### ISSUE TITLE
Swipes and long press input

### ISSUE THREAD

**Issue by noenic** [keymapperorg/KeyMapper#1081]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

Hi, at the moment we can tap the desired location on the screen but we can't stay pressed.

the command is in adb `input touchscreen swipe x y x y delay`. 
this would allow us to do both long presses by executing a swipe with the same start and end coordinates or a real swipe with different start and end coordinates.

**Comment by sds100** [comment]
implemented in #1158
