### ISSUE TITLE
Razer Kishi: Support special buttons

### ISSUE THREAD

**Issue by ozboss** [keymapperorg/KeyMapper#1089]
I recently got the Razer Kishi (V2) and I would like to be able to remap the special buttons (Share Button, Razer Nexus Button).
Unfortunately when running 'Record trigger' the timer just runs out without recognizing these keys.

Is it possible to support them?
Can I provide some debug information?

BTW: Thank you for this incredibly polished app :)

**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Comment by ozboss** [comment]
I was afraid this would be the case. My phone is currently not rooted, but I might try it with my old phone.
Is there a particularly good guide you can point to? Anyway I can figure out which keys I want to change in the key file?

**Comment by sds100** [comment]
If you aren't rooted then I don't think there is a solution :(
