### ISSUE TITLE
Allow mapping of Samsung Galaxy side key

### ISSUE THREAD

**Issue by DavidEGx** [keymapperorg/KeyMapper#1097]
Just bought a Samsung Galaxy S22, I tried to map the _side key_ with KeyMapper and it doesn't work. I guess you might wonder what is the _side key_...

> If you can’t find the Power button on your Galaxy phone, don’t panic. Depending on your phone model, there won’t be a separate Power and Bixby button. Instead, they have been combined to create the Side key! This key can be programmed to perform different tasks, such as turning off your phone, calling Bixby, or opening an app. 

so basically is the power button ¯_(ツ)_/¯.

Samsung allows some limited options to configure:

![Side key screen config](https://i.imgur.com/WKSwk3E.jpeg)

I'd like to map _side key_ long press to toggle torch.
Not enough options in default Samsung config :(
Side key press not detected In KeyMapper :(

Mapping this key should probably throw some extra warnings, especially if someone tries to map short press. That could lead to someone not being able to wake up the phone.

**Comment by GL513** [comment]
Hello, please see #680
Is this the same as what you are hoping for?

**Comment by sds100** [comment]
implemented by #1297
