### ISSUE TITLE
Android TV crash

### ISSUE THREAD

**Issue by OTSUKAKK** [keymapperorg/KeyMapper#1102]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

Nice app, but can you please make this app compatible with Android TV?
I have slideload this app on Android TV and when try to add button, it force closed.

**Comment by sds100** [comment]
Can you follow this guide to report a bug https://docs.keymapper.club/report-issues/
