### ISSUE TITLE
Exporting/Importing a keymap that can be triggered by other apps should preserve its UID

### ISSUE THREAD

**Issue by sudomain** [keymapperorg/KeyMapper#1120]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
I know the app is no longer developed, but if someone knows the import/export code, I think this should be fixed: I trigger some of my keymaps using shell scripts in Termux using the `am` tool:
`am broadcast -a io.github.sds100.keymapper.ACTION_TRIGGER_KEYMAP_BY_UID --es io.github.sds100.keymapper.EXTRA_KEYMAP_UID 48df9264-da54-4bab-af80-ea53e1a70782`

But if the keymaps were recently exported and imported (for example when migrating to a new Android device), then their UIDs change. My scripts stopped working which wasn't a big deal. I just copy/pasted the new UID's into the scripts and it only took a few minutes. It's just another step involved in a rare event such as a device migration, but since keymaps are given UIDs, they should probably be preserved.

**To Reproduce**
1. Export keymaps with uids/triggered from other apps
2. Import keymaps

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T] Pixel 2
 - Android version: [e.g. Android 10] 11

**Additional context**

**Comment by sds100** [comment]
Since it is a *universal* unique identifier then I shouldn't even need to update the ID for conflict reasons. I'm thinking that I just overwrite any key maps that have the same UID, what do you think? The only situation where this would happen is if the same person exports and then imports the key maps they *already* have, which is quite unusual.

**Comment by sudomain** [comment]
True. I was overthinking a somewhat contrived scenario with my message above 😆

**Comment by sds100** [comment]
implemented
