### ISSUE TITLE
2.4.5 instantly crashes on Uniherz Titan

### ISSUE THREAD

**Issue by sakhmatd** [keymapperorg/KeyMapper#1148]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Describe the bug**
After updating to 2.4.5, the app instantly crashed and disabled my keyboard. I attemped to uninstall and reinstall the app and noticed that this happens when I enable accessibility for it or whenever I simply continue through the setup prompts.

When I downgraded back to 2.4.4, the app works as usual.

**To Reproduce**
1. Update to 2.4.5 from 2.4.4
2. Activate accessibility service for the app or simply continue through the setup prompts without enabling the service.

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)
Irrelevant as app crashes when freshly installed with no keymaps.

**Expected behavior**
It shouldn't crash.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Uniherz Titan
 - Android version: 9

**Additional context**
N/A

**Comment by sds100** [comment]
I can confirm this is a bug. I'll fix it

**Comment by sds100** [comment]
fixed
