### ISSUE TITLE
Accessibility service doesn't start

### ISSUE THREAD

**Issue by junetried** [keymapperorg/KeyMapper#1153]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
The accessibility service crashes immediately. The quick start screen says that the service has been killed or has crashed. Completing the quick start causes the app to crash. When I upgraded from a previous version with existing key maps, the app would crash on startup.

**To Reproduce**
Install a Key Mapper version after 2.4.4, then open the app and walk through the quick start until it asks to enable/restart the accessibility service.

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)
(This is not possible and doesn't seem related.)

**Expected behavior**
The accessibility service starts after enabling it and completing the quick start brings me to the main configuration screen.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - Android version: Android 12

**Additional context**
I can reproduce this issue on 2.4.6 and 2.4.5, but not 2.4.4.

**Comment by nahuhh** [comment]
245 was broken for me. 246 (fresh install) worked
android 10

**Comment by sds100** [comment]
2.4.6 should fix this issue

**Comment by junetried** [comment]
I just checked again, and 2.4.6 works. I thought I was using 2.4.6 at first, but the latest F-Droid build is 2.4.5, so I was not.
