### ISSUE TITLE
Unable to record Boox Leaf buttons

### ISSUE THREAD

**Issue by gerwitz** [keymapperorg/KeyMapper#1154]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
I have a first-generation Boox Leaf (e-ink tablet) with a case that includes "page turn" buttons that are generally recognized as volume buttons. E.g. the Amazon Kindle app sees them as volume up and volume down.

In Keymapper, when I press them on the "Record a trigger" screen, nothing happens.

I cannot find any useful information except for [one Reddit mention](https://www.reddit.com/r/Onyx_Boox/comments/roih6q/comment/i5zh1xw/?utm_source=share&utm_medium=web2x&context=3)

**To Reproduce**
Install Keymapper on Leaf, launch, configure accessibility, use the + button to try and record a keymap, press volume buttons. The system overlay for volume changes appears, the app does not change state.

(I cannot create a keymap so have nothing to upload)

**Expected behavior**
Well, something to happen.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Boox Leaf (1st gen)
 - Android version: 10

**Additional context**

**Comment by sds100** [comment]
It seems like they don't send these button presses to the accessibility services so there isn't anything we can do to monitor these key presses unfortunately. My record trigger button does _no_ filtering unlike in other apps so if it doesn't show up then its the system's filter causing the issue. :(
