### ISSUE TITLE
Bug (serious issue please reply)

### ISSUE THREAD

**Issue by SkJarir** [keymapperorg/KeyMapper#1156]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
A clear and concise description of what the bug is. I selected w of my keyboard to move forward and i selected space to jump but the problem is i can't jump while walking and i can't move while jumping it means not working tow key press in same time i used tap on screen 
Featur 

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here] (sorry because iam new here i hope i will learn about this in future)

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I used ![Screenshot_2023-08-25-13-49-37-77_9c8362cc5290d10886fd53faced8c103.jpg](https://github.com/keymapperorg/KeyMapper/assets/143168667/29038f34-2958-4196-84ae-f7b0e452c6cc)

**Smartphone (please complete the following information):**
 - Device: [Realme 6]
 - Android version: [Android 11]

**Additional context**
Add any other context about the problem here. If it not possible in this Android version then tell me that and also why it's not working please tell me that I want to learn thanks

**Comment by sds100** [comment]
https://docs.keymapper.club/user-guide/actions/#tap-screen-210-android-70 this is a known issue that cant be solved because Android doesn't allow it

**Comment by SkJarir** [comment]
Sir in panda mouse pro there is an option called activation by usb
debugging with this command >sh /sdcard/.chaozhuo.gameassistant2/inject.sh<
