### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Tridays** [keymapperorg/KeyMapper#1166]
May I ask how you monitor the key codes of a soft keyboard, such as the window key? Can you provide me with a code example? I need your help
![2f69cf599a503277a1d3c7b1c29726f](https://github.com/keymapperorg/KeyMapper/assets/127336245/373321e8-41ff-4c7c-8a04-98ae175fb812)

**Comment by sds100** [comment]
Hi, if the button doesn't show up as a trigger then unfortunatly it isn't possible to remap it. Some devices behave strange and different to other ones 🤷‍♂️
