### ISSUE TITLE
The "string array" extra in the "Send intent" action dialog can't be saved

### ISSUE THREAD

**Issue by Codereamp** [keymapperorg/KeyMapper#1171]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
The "Send intent" action has a feature-rich dialog allowing supplying different type of data including extras. The string type works as expected. Although "string array" type allows filling the fields, but after clicking the accept button and returning later to the same editing dialog, the "string array" extra just provided, is not present. I'm not sure about other types since I tried only "string" and "string array"

**To Reproduce**
- create new "Send intent" action, 
- in the opened dialog go to Extra section and click at "add extra", choose "string array"
- fill the fields in the appeared section 
- tap "accept" button at the right bottom part of the screen
- In the newly added line about this action tap the edit button then "Edit action". See that the newly added "string array" section is absent

**Expected behavior**
The added section should be present as other types of extra data. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Nook Glowlight 4
 - Android 8
 
**Additional context**

**Comment by sds100** [comment]
I'm fixing this today!
