### ISSUE TITLE
The "screenshot" action doesn't obey "Show an on-screen message" setting

### ISSUE THREAD

**Issue by Codereamp** [keymapperorg/KeyMapper#1190]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Describe the bug**
Version 2.6.0.
The "screenshot" action doesn't obey "Show an on-screen message" setting. It always show the message regardless of the setting.

**To Reproduce**

- Add a macro with "screenshot" action, 
- leave  "Show an on-screen message"  unchecked
- Perform the action somewhere, the message "Screenshot taken" is shown

**Expected behavior**
The setting should be obeyed.

**Smartphone (please complete the following information):**
 - Nook Glowlight 4e
 - Android 8

**Additional context**
Actually I didn't care for the setting, but the message appeared on the screenshot itself, so I had to try to disable it, but the unchecked setting meant that it wasn't supposed to be shown in the first place. I supposed the message on the screenshot has nothing to do with KeyMapper, but with how eInk screens redraw and delays actions But just in case I suggest to look once more at the sequence of actions so first screenshot, then the message (If it doesn't break some other things :)

**Comment by sds100** [comment]
I will just add a 3 second delay after taking the screenshot.

**Comment by sds100** [comment]
fixed
