### ISSUE TITLE
collapse status bar failed, failed perform global action 15

### ISSUE THREAD

**Issue by suishixingkong** [keymapperorg/KeyMapper#1194]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
collapse status bar is failed.
Failed perform global action 15!

**To Reproduce**

Upload a backup of your keymaps. 
Version 2.6.0

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel C
 - Android version: Android 13

**Additional context**

**Comment by sds100** [comment]
I can confirm this a bug! I will fix it but I may have to remove the action from Android 13 if Android doesn't allow apps to do this anymore :(
