### ISSUE TITLE
Delay when inputting key events through input method on Android 14

### ISSUE THREAD

**Issue by Jittyo** [keymapperorg/KeyMapper#1218]
**Developer TODO**
- [x] Keep legacy method of sending key events for < Android 14 and remove it once everyone has updated to the new system.
- [x] Test with having multiple key mapper input methods enabled because using the same relay service

Al actualizar android 14 ya no funciona fluido va trabado al  es como si solo funcionará la mitad yo apretó para que comienze y no va fluido

**Comment by Bsjsu** [comment]
Pro, I am suffering from this problem after the update, but no one responds to us

**Comment by sds100** [comment]
Hi, I'm confirming this a bug and I'll fix it very soon. :)

**Comment by Bsjsu** [comment]
Hello, is the problem solved or not?

**Comment by Bsjsu** [comment]
> مرحبًا، أؤكد هذا الخلل وسأصلحه قريبًا جدًا. :)
Is the problem solved ?

**Comment by sds100** [comment]
For future reference: source of the problem https://developer.android.com/about/versions/14/behavior-changes-all#pending-broadcasts-queued
