### ISSUE TITLE
Key Mapper notifications can't be enabled on Android 14

### ISSUE THREAD

**Issue by Chromastin** [keymapperorg/KeyMapper#1219]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
The screenshots show that notifications from key mapper cannot be received due to notification blocking, which cannot be bypassed. I can't allow notifications to arrive either, no matter how hard I try. Perhaps it's the software, because on the last samsung m31 phone, all notifications were transferred without problems. I need notifications to quickly change the keyboard, if there is a way, could you tell me?

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**
I wanted to see a notification through which I could quickly change the keyboard.

**Screenshots**
![Screenshot_2024-05-29-15-30-00-67_8142442b4340f41fb3bd44535ad8f76b](https://github.com/keymapperorg/KeyMapper/assets/171214120/55b8bb56-0746-4011-94ce-7e18f767c54b)
![Screenshot_2024-05-29-20-44-04-39_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/keymapperorg/KeyMapper/assets/171214120/3f534cd6-a568-49bd-90ef-6956731f2915)

**Smartphone (please complete the following information):**
 - Device: [Realme c55(rmx3710)]
 - Android version: [Android 14(the newest update version of my phone)]

**Additional context**

**Comment by sds100** [comment]
This is a bug on Android 14 in general, I'll fix this soon!
