### ISSUE TITLE
Bug: Key Mapper only executes the oldest shortcut that it knows about from the app "HTTP Request Shortcuts"

### ISSUE THREAD

**Issue by sudomain** [keymapperorg/KeyMapper#1222]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
I was hoping to use the shortcuts from app [HTTP Requests Shortcuts](https://f-droid.org/packages/ch.rmy.android.http_shortcuts/) in order to send HTTP requests for certain keys. There is a bug where if two or more of the shortcuts from this app are used as Key Mapper actions, only the older one will get executed. In the following example, the "Button_L1" shortcut will get executed for both mappings:
![Screenshot_20240605-185919](https://github.com/keymapperorg/KeyMapper/assets/30786326/a609eaf0-3e20-43fa-a78a-d1b05fbd604d)

When selecting a shortcut, the HTTP requests app allows selecting "Default" or "Legacy" placement method: 
![Screenshot_20240605-183513](https://github.com/keymapperorg/KeyMapper/assets/30786326/5cc262c0-d506-4223-b2fc-6d7f7c95234d)
If "Default" is used, then the keymapper action will give a toast with a message of `Error opening this app shortcut`. However, if `Legacy` is used, we encounter the overwriting bug I described above.

**To Reproduce**
1. Install HTTP requests shortcuts app
2. Create 2 or more shortcuts in that app. It doesn't matter if the request itself is valid because the wrong shortcut is opened and it shows the wrong shortcut name (Button_L1 in my example)
3. Try to run the Button_R2 shortcut/action, either using the trigger or tapping on the action

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)
[button_l1_r1_http_shortcuts_bug.zip](https://github.com/user-attachments/files/15597760/button_l1_r1_http_shortcuts_bug.zip)

**Expected behavior**
The correct shortcut to get run, instead of the oldest one key mapper knows about from the app. Maybe the "Default" shortcut type can be supported? I think these are called "widgets" and can be renamed?

**Screenshots**
See above

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - Android version: Android 11

**Additional context**

**Comment by arpanghosh8453** [comment]
Yep, I am having the same issue with Macrodroid shortcuts.

**Comment by sds100** [comment]
Can you upload a backup of the key map here? I want to see the shortcut data.

**Comment by arpanghosh8453** [comment]
Thank you so much for responding! This will solve my problem big time if it works out :)

I have opened a separate issue too to get some extra attention here #1307 haha. 

I am not sure if it remembers the old one only or the newest one only, but you can see from the JSON file [data.json](https://github.com/user-attachments/files/17178631/data.json) attached that the targets are different. still, it launches the same macro on both triggers. 



![screenshot](https://github.com/user-attachments/assets/83e3256d-95f1-4df9-9e37-4416b8f743e7)

**Comment by sds100** [comment]
Fixed :)

**Comment by sudomain** [comment]
Thank you. @arpanghosh8453 what is "Control Root" in your screenshot. I'm curious.

**Comment by arpanghosh8453** [comment]
No problem @sudomain. This issue was stale for a while, it just got traction today due to my report (in addition to yours) 

The "Control Root" is a [Flipper Zero](https://flipperzero.one/)  BT-Controller (emulated)
