### ISSUE TITLE
action: send intent extra arrays are not saved

### ISSUE THREAD

**Issue by sudomain** [keymapperorg/KeyMapper#1224]
[**Developer](url) TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
When using a send intent action containing an extra which is any of the array types (string, integer, boolean, etc.), the extra gets discarded when the user presses the checkmark. There seems to be some input validation going on for some of the extras such as boolean arrays and integer arrays.

**To Reproduce**
1. Create a send intent action
2. Add an extra of any of the array types
3. Tap the checkmark/save button
4. Open the action for editing and notice the array has been discarded

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**
Array extras should be not be silently discarded.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T] pixel 2
 - Android version: [e.g. Android 10] android 11

**Additional context**

**Comment by sds100** [comment]
I think I fixed this already in #1172 ? Can you check the latest testing build

**Comment by sudomain** [comment]
Confirmed fixed in the testing build. Thank you very much
