### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by Bsjsu** [keymapperorg/KeyMapper#1230]
I'm having a problem updating Android 14 It is the delay. When I press the key, after a few seconds, the computer has to click on me and the required command is executed literally. I am facing the most difficult problem in my life. I hope you find a solution. **Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by sds100** [comment]
Hi, we've acknowledged this issue and are working on it. See #1218 #1229
