### ISSUE TITLE
name triggers

### ISSUE THREAD

**Issue by yotamguttman** [keymapperorg/KeyMapper#1238]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

add custom names to triggers. it'll make them much easier to identify. 
hope this isnt an existing issue, I couldn't search for it.

**Comment by sds100** [comment]
Hi, its been an idea for a while but never got around to it :). See #701
