### ISSUE TITLE
The Android 14 version brings delay and no admin in dc help 

### ISSUE THREAD

**Issue by XFAX14** [keymapperorg/KeyMapper#1240]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**

Bring deley and it doesn't work 
**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**
Bring delay
**Screenshots**
Lo tengo en video 

**Smartphone (please complete the following information):**
 - Device: Motorola g 2023
 - Android version: 14

**Additional context**
Please fix the bug for Android 14 bring deley

**Comment by sds100** [comment]
Yes, this is being fixed. See #1218
