### ISSUE TITLE
New button usable while screen is off

### ISSUE THREAD

**Issue by Spiralo-Idioide** [keymapperorg/KeyMapper#1252]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

Hello, I'd like to propose a new button to be usable when the screen is off. It corresponds to the red button of Original Unihertz Titan (at least using the gargoyle-gsi custom rom). Device is rooted.

Reported as `Camera` in the GUI, and `KEYCODE_CAMERA` in the logs. 

Output for `getevent -lq` (result is identical when the screen is off or on)
```
/dev/input/event1: EV_KEY       00fa                 DOWN                
/dev/input/event1: EV_SYN       SYN_REPORT           00000000            
/dev/input/event1: EV_KEY       00fa                 UP                  
/dev/input/event1: EV_SYN       SYN_REPORT           00000000   
```

Thank you a lot for this software !

**Comment by sds100** [comment]
implemented :)
