### ISSUE TITLE
Add updated translations, Chinese Simplified and Russian

### ISSUE THREAD

**Issue by guobao2333** [keymapperorg/KeyMapper#1256]
**Developer TODO**
- [x] specify language for bydariogamer
- [x] Add badges for languages section in README and on website home page. https://store.crowdin.com/bds

I think you should approve and merge the translated languages into the project, because even if these translations are poor, at least these languages have translations.

Besides, the translation degree of some languages has reached 100%, but you haven't even approved even one word.

Although it is your freedom not to approve, I will be very sad as a contributor, because it is no different from my contribution being rejected.

@sds100 **I hope you can consider it carefully!!** Finally, thank you for your open source work.

**Comment by sds100** [comment]
@guobao2333 Did you contribute a lot of translations for a language?

**Comment by guobao2333** [comment]
> @guobao2333您是否为某种语言的翻译贡献了很多？

Not a lot, But I saw in Crowdin that many parts of many were not approved, even 1% were not.
you may have forgotten the approval work. You can write an automated github actions for this purpose.

**Comment by sds100** [comment]
I've merged the almost complete languages :)
