### ISSUE TITLE
Two mappings conflict (but logically they don't), and the first one was not executed as expected.

### ISSUE THREAD

**Issue by lkchx123** [keymapperorg/KeyMapper#1271]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**
email: 1274578192@qq.com

**Describe the bug**
Two mappings conflict (but logically they don't), and the first one was not executed as expected.

**To Reproduce**
As shown in the screenshot of the mappings, the first mapping won't be executed on any page. While the second mapping can be executed in Bilibili (in line with the settings).

Upload a backup of your keymaps. 
[mappings_20240808-063240.zip](https://github.com/user-attachments/files/16534839/mappings_20240808-063240.zip)

**Expected behavior**
On any page except those in the Yuzu application, the X button should be mapped as the flashlight on. On the pages in Bilibili, double-clicking the X button should be mapped as volume down.

**Screenshots**
![Screenshot_2024-08-08-06-34-09-244_io github sds100 keymapper](https://github.com/user-attachments/assets/d822f586-4b55-43e0-aca2-49ed5ae95418)

**Smartphone (please complete the following information):**
 - Device: Redmi K70
 - Android version: Android 14

**Additional context**
[key_mapper_log_20240808-064233.txt](https://github.com/user-attachments/files/16534891/key_mapper_log_20240808-064233.txt)

This is the execution log (including the extra log) 
. I clicked the X button in the Bilibili application. The first mapping was not executed. Then I double-clicked the X button and the second mapping was executed. Besides, if the second mapping is turned off, the first mapping can be executed normally. Therefore, they conflict.

**Comment by sds100** [comment]
Bug confirmed :)

**Comment by sds100** [comment]
fixed
