### ISSUE TITLE
Bluetooth toggle/enable/disable doesn't work

### ISSUE THREAD

**Issue by Teloshav** [keymapperorg/KeyMapper#1272]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Describe the bug**
Any key maps which does anything to bluetooth just doesn't do anything.

**To Reproduce**
1. Create key map which has actions to do anything to Bluetooth (toggle/enable/disable).

2. Try use the keymap.

**Expected behavior**
Bluetooth status to change.

**Screenshots**
N/A

**Shortcut File**
[key_maps_20240810-215031.zip](https://github.com/user-attachments/files/16569782/key_maps_20240810-215031.zip)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - Android version: Android 14

**Additional context**
N/A

**Comment by sds100** [comment]
Hi, unfortunately Android doesnt support this feature anymore since Android 13. In the next release this will be made clear, see #1227
