### ISSUE TITLE
UI is blocked, unable to click confirm

### ISSUE THREAD

**Issue by iampeony** [keymapperorg/KeyMapper#1280]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

I compiled this project and found an issue. This module Android: id="@+id/fab" should be after Android: id="@+id/appBar", otherwise fab will not be visible and cannot be clicked to save. The affected UI controls include fragment_comfig_key_cevent.xml, fragment_pick_coordinate.xml,fragment_pinch_pick_coordinates.xml,fragment_swipe_pick_coordinates.xml。 This software is really great, it perfectly solves the mapping of my car's infotainment button functions, very convenient and practical!

**Comment by sds100** [comment]
Hi, fixed this in version 2.6.2. See #1293
