### ISSUE TITLE
Click lagging 

### ISSUE THREAD

**Issue by TheRen121** [keymapperorg/KeyMapper#1281]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

Hey,
There's a glitch or something I don't know in keymapper like it lags between click like you know before it use to clicks continuously without any lags perfectly but now the input stops then click then stops for a little bit but it happens which is really annoying i tried every thing like managing the sliders of repeat time (me) and everything but it still like that the input stops then world then stops then works for a short while 

Android 14

Thank you

**Comment by sds100** [comment]
See #1218
