### ISSUE TITLE
Unable to allow KeyMapper access to Shizuki (Google Pixel 8)

### ISSUE THREAD

**Issue by iam-best** [keymapperorg/KeyMapper#1284]
When I give KeyMapper access to Shizuki it just crashes when I reopen KeyMapper (Android 14) (Google Pixel 8) **Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by sds100** [comment]
Can you send a log? I have no issues on Pixel 7, Android 14, with Shizuku. https://docs.keymapper.club/report-issues/

**Comment by iam-best** [comment]
Hey, issue resolved on the test build. The issue is fixed!

Seth Schroeder ***@***.***> schrieb am So., 29. Sept. 2024,
14:05:

**Comment by sds100** [comment]
Ah, great! I'll close this
