### ISSUE TITLE
Add the Rocktek RT-G2 to the list of compatible devices

### ISSUE THREAD

**Issue by HDCP** [keymapperorg/KeyMapper#1286]
Is it possible to have the Rocktek RT-G2 Android TV box added to the list of compatible devices for this application so that it can be downloaded through the Google Play store?

The RT-G2 is a Google-Certified Android TV box with a S905X4 Quad Core CPU.

**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Comment by sds100** [comment]
Hi, the Android TV play store is a separate system to the mobile one so I would have to submit my app for review there. The Key Mapper UI isnt optimized or tested for TV at all so i dont think it will be accepted. See #121 for what needs doing
