### ISSUE TITLE
alternative apps or forks

### ISSUE THREAD

**Issue by 58673** [keymapperorg/KeyMapper#1291]
The application is in maintenance mode, the issue is for any alternatives or maintained forks.

>**Project in maintenance mode.**
>
 >   Well, working on this project was a fun ride 🎢! This project has taught me so much about Android, software development and how to collaborate with an online community. It has been my dream to lead a big FOSS project with people from all over the world so a huge thank you goes to everyone that spread the word and helped on GitHub along the way ☺. Unfortunately, I do not have any more time to work on this project - I'm now studying Computer Science at university and I have landed software-dev side jobs, which has taken up any free-time I did have to code on the side.

**EDIT**: [The app received at least tentative Android 14 support in early September 2024](https://github.com/keymapperorg/KeyMapper/blob/HEAD/CHANGELOG.md#4-september-2024) and the readme was edited; closing the issue.

> **Project under slower development.**

**Comment by Imold** [comment]
It's not open source but there is [Button Mapper](https://play.google.com/store/apps/details?id=flar2.homebutton).
