### ISSUE TITLE
Automatically stop service after specific task done 

### ISSUE THREAD

**Issue by HusniMuhammad** [keymapperorg/KeyMapper#1299]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

Automatically  stop service after specific task done if this task triggerd from shortcut

- To improve battery life

**Comment by sds100** [comment]
This service doesn't impact battery life because it doesn't do much. You can pause your key maps if you really want the service to do absolutely nothing

**Comment by HusniMuhammad** [comment]
Is it possible add **pause** & **exit** option in action section of this app or suggest intents to trigger?

**Comment by sds100** [comment]
You can create an intent to pause your key maps here https://docs.keymapper.club/user-guide/controlling-mappings/#intent-api-230
