### ISSUE TITLE
How to map acute accent

### ISSUE THREAD

**Issue by iasj** [keymapperorg/KeyMapper#1301]
I'd like to know how to map some key combo to perform an acute accent onto any letter pressed after. Like:

á, é, í, ó and ú.

I couldn't find any keycode for it in the actions tab when I look in the "Input key code" button.

I have a new BT keyboard that does not come with a dedicated key for it.

**Comment by sds100** [comment]
Hi, you can either use a Key Event action and turn on the relevant modifier keys such as Ctrl, Shift to do this, or you can just use the Text action and put the accent key in there
