### ISSUE TITLE
[REQUEST] Macro names.

### ISSUE THREAD

**Issue by devanteweary** [keymapperorg/KeyMapper#1303]
Hey this is actually a request.  

App is amazing.  
Just would like to request adding the ability to title our macros.  

I have so many, it's kinda confusing knowing which one is for what at a glance!

So for instance, I have one that goes Home if I'm in ES-DE. So I'd name it "Home in ES-DE".

Thank you!!

**Comment by sds100** [comment]
Hi, I'm glad you like the app and this feature has been highly requested for a few years 😅 See #701

**Comment by devanteweary** [comment]
> Hi, I'm glad you like the app and this feature has been highly requested for a few years 😅 See #701

Can't live without it (the app that is). :P'
