### ISSUE TITLE
您好！这是一位中国用户对该APP的反馈！

### ISSUE THREAD

**Issue by BestPVPNa1Xue** [keymapperorg/KeyMapper#1310]
设置一个循环输出keycode_q、间隔30ms的动作，使用shizuku运行，并且把键盘切换到其它的输入法，会导致屏幕失灵，产生很大的延迟，无法达到间隔30ms的目标速率，希望能够优化一下！这对我来说真的很重要！😊

**Comment by sds100** [comment]
If you're on Android 14 update to version 2.6.2 and see if it is fixed
