### ISSUE TITLE
Potential crash on Android 14

### ISSUE THREAD

**Issue by Ralegend-bit** [keymapperorg/KeyMapper#1311]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**A

**Comment by Ralegend-bit** [comment]
Hey Keymapper team!
In Andriod 14 Keymapper Getsbvery Kuch stucks and crash I use Keymapper for Minecraft so it gets so much stuck and crash I get this problem when I use Keymapper and play Minecraft I get this problem in 2min always plz fix it fast my request🙏😭😭😭

**Comment by sds100** [comment]
stale
