### ISSUE TITLE
[SUPPORT] Repeat not working - possible bug or human error

### ISSUE THREAD

**Issue by Jamie333x** [keymapperorg/KeyMapper#1313]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**
jamiesayegh@gmail.com 

**Describe the bug**
I created a basic keymap for a game that works perfectly on single use. The issue is automation. When I enable repeat regardless of delays I have in place the entire thing goes haywire and the variables are out of order.  If press T is at the start for some reason when I use repeat only T is spammed.

**To Reproduce**
See screenshots, will upload video on request if my keymap seems correct.

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**
I just want the keymap to perform continuously in the same order they are placed even with repeat. 
1 > 2 > 3 > 4  and repeat not 1 > 3 > 2 > 4. How can I get my key map to work consecutively and repeat constantly until disabled. Fyi it works fine with repeat off.

**Screenshots**
![Screenshot_20241003_093403_Key Mapper](https://github.com/user-attachments/assets/34d9e1be-14cf-4fec-b95e-437fb00f0399)
![Screenshot_20241003_093409_Key Mapper](https://github.com/user-attachments/assets/52c84269-e89c-4ec1-9dca-33f66ddef071)

**Smartphone (please complete the following information):**
 - Device: Samsung
 - Android version: S22 Ultra

**Additional context**

**Comment by sds100** [comment]
Hi, I guess this could be construed as a bug but when I think about how I'd fix it it would be quite complicated. The issue is Key Mapper behind the scenes repeats each action separately, it doesn't consider the order. This is because let's say you had one repeating at 15ms and another at 20ms. In your case you set them all to the same repeat delay, and it's impossible for a computer to do execute them all exactly at the same time anyway. So just add a 50ms offset to each one and it should work?

**Comment by Jamie333x** [comment]
You're a legend mate. The script faults on first and second run then it's flawless indefinitely. Thankyou so much. 
Just a quick vid of my success 
https://cdn.discordapp.com/attachments/1291017541963087953/1291322124358783037/Screen_Recording_20241003_184833_Minecraft.mp4?ex=66ffacf2&is=66fe5b72&hm=f8fb3839be4dcd98984b5b546839f002cf0d75f962696a51a09633cc40279fab&

**Comment by sds100** [comment]
Thank you 😎
