### ISSUE TITLE
the keyboard mapping doesn't work it says that the assesibelity setting is on and it doesn't work

### ISSUE THREAD

**Issue by gowthamkodali27** [keymapperorg/KeyMapper#1319]
[key_mapper_report_20241009-211748.zip](https://github.com/user-attachments/files/17320420/key_mapper_report_20241009-211748.zip)
**Developer TODO (don't remove)**
- [ ] write tests. put issue number in comment
- [ ] update documentation

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by sds100** [comment]
It looks like you are using a Chromebook and we don't officially support them because I can't reproduce any issues. Does this also happen on your phone?
