### ISSUE TITLE
Single-character non-ASCII TEXT_BLOCK input crashes the service.

### ISSUE THREAD

**Issue by t184256** [keymapperorg/KeyMapper#1328]
**Developer TODO (don't remove)**
- [ ] write tests. put issue number in comment
- [ ] update documentation

**Discord message link/email recipient**

**Describe the bug**
Single-character non-ASCII TEXT_BLOCK input crashes the service.

**To Reproduce**
Steps to reproduce the behavior: On Android 14 (with that new-fangled proxy thing) use TEXT_BLOCK with a single non-ASCII character.
[mappings_generated.json](https://github.com/user-attachments/files/17542601/mappings_generated.json). Two characters work fine because they take a different code path.

**Expected behavior**
Single character is inputted fine.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - Android version: Android 14 (LineageOS)
 - Also observed on Samsung Tab S8 Ultra / Stock Android 14

**Additional context**
IMO, when `keyCharacterMap.getEvents(chars)` in `inputTextRelayService` returns null, [there should be a fallback](https://github.com/keymapperorg/KeyMapper/pull/1237/files#diff-d466bf0542a8a7aabec5120669119f05f34591e72d68dc7bfdce1afc02fe54deR166).

**Comment by t184256** [comment]
Such crashes were never a problem on a Samsung Fold 2 / Android 13.

**Comment by t184256** [comment]
Yes, with that build no longer crashes and outputs cz/ru just fine. Thank you!

**Comment by sds100** [comment]
great! Will mark as fixed
