### ISSUE TITLE
Bluetooth support 

### ISSUE THREAD

**Issue by Orlandofurioso91** [keymapperorg/KeyMapper#1329]
**Developer TODO (don't remove)**
- [ ] write tests. put issue number in comment
- [ ] update documentation

**Discord message link/email recipient**

**Describe the bug**
Bluetooth toggle needs root with Android 13 Unihertz jelly since version 2.6 With version 2.5 Bluetooth toggle works fine

Roland.heggli@posteo.ch

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by sds100** [comment]
It won't be possible to implement this without root because the API was deprecated on Android 13+. https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#enable()
