### ISSUE TITLE
It may not work if the model is different.

### ISSUE THREAD

**Issue by Take1932** [keymapperorg/KeyMapper#1355]
It worked on the Pixel 7 Pro (Android 15) that I used before, but it doesn't work on the Pixel 9 Pro XL (Android 15) that I'm using now.
The settings are the same.

**Comment by sds100** [comment]
Can you give more info, what doesn't work exactly?

**Comment by fortimax** [comment]
it's not starting at all on Google pixel 9 pro max

**Comment by sds100** [comment]
I will need much more information @fortimax if i want to fix this. I will close this and you should create another issue and fill in the bug template.

**Comment by Take1932** [comment]
Sorry for the late reply. Yes, I thought it was a problem with the model, so I reset the keyboard and was able to take screenshots. Thank you.
