### ISSUE TITLE
my dpad not triggering 

### ISSUE THREAD

**Issue by mkmoneer** [keymapperorg/KeyMapper#1363]
**Developer TODO (don't remove)**
- [ ] write tests. put issue number in comment
- [ ] update documentation

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by sds100** [comment]
This is expected behavior as defined in https://docs.keymapper.club/faq/
