### ISSUE TITLE
2.7.0 Bug: Crash when using "Input key code" action

### ISSUE THREAD

**Issue by Software27425** [keymapperorg/KeyMapper#1364]
**Developer TODO (don't remove)**
- [ ] write tests. put issue number in comment
- [ ] update documentation

**Describe the bug**
2.7.0 crashes when performing an "input key code" action. Downgrading to 2.6.2 fixes the issue.

**To Reproduce**
Make the following key map:
Trigger: w key
Action: Input KEYCODE_ENTER

Then activate trigger by pressing w on keyboard. Crash occurs.

**Expected behavior**
Pressing w on my keyboard should perform an "enter" keypress.

**Smartphone (please complete the following information):**
 - Device: Motorola Edge 2023
 - Android version: 14

**Additional context**
The crash only happens in 2.7.0. Downgrading to 2.6.2 and doing the same steps described above fixes the issue. And yes, my accessibility and shizuku settings were enabled for each version.

**Comment by sds100** [comment]
fixed

**Comment by Software27425** [comment]
Can confirm the fix is working in test build 2.7.1-ci.122 :D Thanks @sds100 ! Hoping to see the next stable release soon :)
