### ISSUE TITLE
Bluetooth device

### ISSUE THREAD

**Issue by VasilKotsov** [keymapperorg/KeyMapper#1374]
**Developer TODO (don't remove)**
- [ ] write tests. put issue number in comment
- [ ] update documentation

**Discord message link/email recipient**

**Describe the bug**
Hello I have this device https://www.aliexpress.com/item/1005007031146528.html?spm=a2g0n.productlist.0.0.2cb044c4oZmhYH&browser_id=885d34242b3f47d28785b024300d7fe2&aff_trace_key=ef1b60afa041411890d8f1d7835bd1d3-1733046924818-09884&aff_platform=msite&m_page_id=mfphvvzlscawrusb193f985f79cc71e27b11d0c095&pdp_npi=4%40dis%21BGN%21102.28%2135.79%21%21%2153.38%2118.68%21%40210390b817350581267271703ecb84%2112000043233043407%21sea%21BG%212726824987%21X&algo_pvid=126bb1d5-73ae-4eb7-9f52-d492f44c9d7f
and I try to trigger the buttons but it doesn't detect any off them at all. Is there any way to fix that. 

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Motorola Edge 40 Pro] 
 - Android version: [e.g. Android 14 LineageOS]

**Additional context**

**Comment by sds100** [comment]
I don't think there is anything we can do. Some Bluetooth devices don't always send key events but rather instructions to play/pause music the same way headphones do, which also don't work with Key Mapper.
