### ISSUE TITLE
Feature request spelling  

### ISSUE THREAD

**Issue by frog-o** [keymapperorg/KeyMapper#166]
I know not your problem but would be realy great for something like this.

Is with hardware keyboards the default Android spell check is horrible for multi-language typing.  

there another project: 

https://github.com/Softcatala/LanguageToolAndroidService 

that a bit better in some ways but does not switch langues.   I would like to switch languages with a key combination like "ctrl + up arrow"

**Comment by sds100** [comment]
Just to clarify, you would want an action which changes the language of whatever keyboard you're using?

**Comment by frog-o** [comment]
That the basic but not changing the keyboard.  I thought you might be able to take the code above add an intent to it to switch languages or create your own spelling service.

**Comment by sds100** [comment]
Okay. I'll look into it but I'm not sure it is possible to change another keyboard's language. When I add the AOSP keyboard into the Key Mapper input method, I'll add support to change the multiselect language.

**Comment by sds100** [comment]
I don't know what this is about 😂 It has been over 3 years
