### ISSUE TITLE
Don't require input method

### ISSUE THREAD

**Issue by hoshsadiq** [keymapperorg/KeyMapper#253]
[Button Mapper](https://play.google.com/store/apps/details?id=flar2.homebutton) is able to do a lot of the current functionality in KeyMapper without root and without requiring it to be set as an input method. Is it possible finding out how Button Mapper does this and implementing a similar mechanism?

Would eliminate the need for #111 while simultaneously giving users choice. Hopefully with less effort.

**Comment by sds100** [comment]
Yeah. I see what you mean. I can't find any actions button mapper has where I have used an input method to do the same thing.

**Comment by hoshsadiq** [comment]
Not sure I follow what you mean. What I'm referring to is that currently (and I appreciate that this might be me only) I am using this on an Android TV. After remapping any key, the only way it'll register the inputs and trigger the configured actions is by setting the Input Method to be KeyMapper's Keyboard, which of course makes the OSK in ATV unusable. This is not the case with Button Mapper. So was hoping that it can be done the same or similar way within KeyMapper, therefore eliminating the need to implement the AOSP keyboard.

**Comment by sds100** [comment]
Oh, okay. Is this the case with ANY action or just actions which require
the key mapper input method to be chosen?

**Comment by PavelGorbanj** [comment]
Hi, any news on this?

**Comment by sds100** [comment]
As far as I'm aware this request isn't possible. I would need someone else to show that it is. One can now use Shizuku in 2.4.0.

**Comment by sds100** [comment]
Any news on how to make this work from anyone? Impossible as far as im aware
