### ISSUE TITLE
Add leanback keyboard Hide/dehide on Android TV

### ISSUE THREAD

**Issue by Bigdut** [keymapperorg/KeyMapper#507]
If I use your app as keyboard to replace some key function of the usb airmouse and I reach a field text (like search) the normal leanback keyboard not popup.
Otherwise if I no select your app as default keyboard, non all keys of airmouse are recognised.

Sony TV android 7.0

**Comment by sds100** [comment]
Hello,

Which actions are you using? Some actions require a compatible Key Mapper keyboard to be used for them to work. The keyboard built-in to Key Mapper intentionally has no GUI/buttons, which is probably why you think the leanback keyboard doesn't popup.

Key Mapper doesn't officially support Android TV yet but I am going to add support. I will also make a Leanback keyboard that is compatible with Key Mapper, like the Key Mapper GUI Keyboard. see #493

**Comment by Bigdut** [comment]
Hi sds100

I wrote you for the Android TV project as suggest. I know that the actual version Is not fully compatible. 

I use your app for thia scope:
On Sony bravia Android TV 7.0
I connect a USB airmouse mimix neo a3 (with microphone)
But the related Key does  not active the voice search so i Need a key remapper to do this.
Now the 2 issues:
- all special keys of the air mouse are recognized as the same Button "0". So i cannot remap the special keys indipendetly. (The others button are recognized likes standard function: menù, home, volume etc etc)
- if the main keyboard Is leanback the special key of the air mouse Is not recognized. If the main keyboard Is your app, the leanback not popping up in the text field.

Another point Is, why some special keys of TV remote controller are recognized by the "record trigger" but not under "add action => Key"?
Under "Key" menu the special keys of the remote are priorized over your app.
In my case this special keys are: guide, Discovery menù , action menù (all connected to the Sony sub sistem)

Thank you so.much for your job

**Comment by sds100** [comment]
Thank you for the info.

The "record trigger" button uses the accessibility service to detect keys whereas "add action => key" uses a different API through the Activity. Some Android systems send key events to Activities but not to accessibility services and vice versa. There isn't anything we can do about that. Luckily for you the accessibility service can still detect those buttons. It is usually the other way around.

So the solution to this problem is to add a Key Mapper compatible leanback keyboard because the Key Mapper keyboard can detect your special keys?

**Comment by Bigdut** [comment]
> So the solution to this problem is to add a Key Mapper compatible leanback keyboard because the Key Mapper keyboard can detect your special keys?

yes!  
After, if possible, recognized all special keys with different "key code". In the past with one key mapper (mkr! if I remember) was possible recognized all keys of the airmouse, other apps (like CMAK) have the same problem and some keys are recognized with the same keycode "0" like your app.  

But it is not urgent. ;P

**Comment by sds100** [comment]
Could you install this app, press the "special keys" and then send a screenshot of the output. I wonder if the scancodes are different but they keycodes are the same.

https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay

**Comment by Bigdut** [comment]
![PXL_20201116_171602938](https://user-images.githubusercontent.com/33321771/99285991-8cc60780-2838-11eb-9429-a0136de109fd.jpg)

**Comment by Bigdut** [comment]
![PXL_20201116_172427263~2](https://user-images.githubusercontent.com/33321771/99286716-8c7a3c00-2839-11eb-8234-109a25fdd352.jpg)
![PXL_20201116_171518444](https://user-images.githubusercontent.com/33321771/99286735-956b0d80-2839-11eb-903c-8437c54a3941.jpg)
![PXL_20201116_172420616](https://user-images.githubusercontent.com/33321771/99286760-9d2ab200-2839-11eb-9897-3f2ec904dc6d.jpg)

**Comment by Bigdut** [comment]
Same order, but differenti keyboard selection:
![PXL_20201116_171700557](https://user-images.githubusercontent.com/33321771/99286829-baf81700-2839-11eb-8990-17e3ac793025.jpg)
![PXL_20201116_171737241](https://user-images.githubusercontent.com/33321771/99286844-c1868e80-2839-11eb-9626-1dd59a7d33b6.jpg)

**Comment by Bigdut** [comment]
![PXL_20201116_171802920](https://user-images.githubusercontent.com/33321771/99286894-d2cf9b00-2839-11eb-9855-79c07a652ebf.jpg)
![PXL_20201116_171826169](https://user-images.githubusercontent.com/33321771/99286905-d7944f00-2839-11eb-9b13-f905a7694b5c.jpg)

**Comment by sds100** [comment]
How come the "code" is 84 when you are using the Key Mapper keyboard? Did you remap that button to KEYCODE_SEARCH?

**Comment by sds100** [comment]
since they have a different scan code, I could add a way for Key Mapper to detect a trigger by its scan code rather than key code. I would need to re-architect quite a bit of the app so it will be quite a bit of work.

**Comment by Bigdut** [comment]
> How come the "code" is 84 when you are using the Key Mapper keyboard? Did you remap that button to KEYCODE_SEARCH?

Yes, Sorry, i forgot to disable .
Tomorrow Ill sand you the correct code

**Comment by sds100** [comment]
See #761
