### ISSUE TITLE
Non ASCII character support in app selection

### ISSUE THREAD

**Issue by UraniumDonut** [keymapperorg/KeyMapper#525]
Currently all apps with non ASCII characters are not shown in the App launch menu of the app. (Example: russian characters in app name) Package name is still conforming to android standards (no spaces, only small ascii characters), just the display name breaks the selection 

Platform: Android TV 
Hardware: Chromecast 2020 with google TV

**Comment by sds100** [comment]
Hi,
On my phone apps with non-ascii names end up at the bottom. I don't have an Android TV and the emulator doesn't allow me to change the language. Is this issue related to #487 ?
![Screenshot_20201230-161851](https://user-images.githubusercontent.com/16245954/103368323-27179d00-4abf-11eb-8db8-006a85e88f72.png)

**Comment by UraniumDonut** [comment]
This could be related to this. The app in question is "TVRain" (дождь). But the app is also available for "regular android" on phones, so it should also have the regular stuff in manifest (?). When I have a chance to check on the manifest values, I can comment back

**Comment by sds100** [comment]
Yeah, if its on phones it probably will have regular stuff as well. So maybe this is a separate issue.

**Comment by sds100** [comment]
I installed the app on my phone and it showed up in the app list. This is almost certainly Android TV specific. I'll try to install it on the Android TV emulator...

**Comment by sds100** [comment]
It shows on my Android TV emulator
![image](https://user-images.githubusercontent.com/16245954/103373798-cfccf900-4acd-11eb-9227-87de6ac7d777.png)

**Comment by UraniumDonut** [comment]
Huh😨

Could it be, that the apk for tv and phone is different? Did you install from the play store?

**Comment by sds100** [comment]
Yeah, that's the phone APK from the play store

**Comment by sds100** [comment]
Send me the TV apj

**Comment by sds100** [comment]
@UraniumDonut is this fixed in the latest build in Github Actions?

**Comment by sds100** [comment]
Not sure what the situation is this with this. @UraniumDonut is this fixed?
