### ISSUE TITLE
Swiping action

### ISSUE THREAD

**Issue by postpersonality** [keymapperorg/KeyMapper#550]
Hi!
Thanks for the awesome app! But after a short usage I cannot get how to make a swipe action including delays or holding for a period of time. Do you have a documentation about that? Many thanks!

**Comment by sds100** [comment]
Hi, there currently isn't a swipe action. I'll rename this to s swipe action feature request.

**Comment by deoxal** [comment]
Thanks for making this app @sds100 sds. If I can get it in gear to learn Android development I'll fork this to make game controllers work for games that don't support bluetooth.

What would your recommendations be to someone whose only done the basics of programming in eclipse? The most I've done was parse and solve arithmetic expressions with a CLI java applet.

**Comment by sds100** [comment]
Hi @deoxal! I've sent you a message on Ko-fi, can you please check that. I'm happy to hear you like the app. 🙂 These are the relevant issues #199 #491 for your feature request. This one has a misleading name. #491 explains how to detect the joysticks as triggers. Android development, especially developing a utility app like Key Mapper, requires a lot of Android-specific knowledge to know what to do. I would start by doing this Android development in Kotlin codelab https://developer.android.com/codelabs/kotlin-android-training-welcome. There are a lot of libraries (like Room, Navigation, Kotlin coroutines) you need to learn to do "modern Android development" as they call it. Key Mapper uses most of these so this is a good place to start. If you have any questions, you can email me at developer.sds100@gmail.com

**Comment by sds100** [comment]
implemented in #1157
