### ISSUE TITLE
No key passthrough

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#676]
Keys won't send after being intercepted with no action. I cant use keys that are mapped for regular use, only for the keymaps.
For example, if i type `~` and I have it mapped to a press hold, it won't pass through.
I expect the keymaps to override something like a double tap (which would usually enter the character twice) and instead preform the action wanted.

**Comment by sds100** [comment]
check if this still happens in the latest alpha build

**Comment by sds100** [comment]
**LOG**

```
12:58:51.169  Down KEYCODE_2, key code: 9, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 10, is external: true, meta state: 0, scan code: 3
12:58:51.182  Down KEYCODE_2 - consumed: true, key code: 9, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 10, is external: true, meta state: 0, scan code: 3
12:58:51.191  Up KEYCODE_2, key code: 9, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 10, is external: true, meta state: 0, scan code: 3
12:58:51.196  Up KEYCODE_2 - consumed: true, key code: 9, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 10, is external: true, meta state: 0, scan code: 3
12:58:53.079  Down KEYCODE_2, key code: 9, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 10, is external: true, meta state: 0, scan code: 3
12:58:53.093  Down KEYCODE_2 - consumed: true, key code: 9, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 10, is external: true, meta state: 0, scan code: 3
12:58:53.599  Performed action TextAction(text=Passthrough test.), input event type: DOWN_UP, key meta state: 0
12:58:53.605  Performed action TextAction(text=Passthrough test.), input event type: DOWN_UP, key meta state: 0
12:58:54.136  Up KEYCODE_2, key code: 9, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 10, is external: true, meta state: 0, scan code: 3
12:58:54.138  Up KEYCODE_2 - consumed: true, key code: 9, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 10, is external: true, meta state: 0, scan code: 3
```

**Comment by lilithium-hydride** [comment]
Still happening on 2.3.1. The app can't seem to replicate Android's native notification/quick settings fingerprint gesture behaviour, so it'd be pretty nice to be able to assign things to the left and right swipes without blocking the normal up and down behaviour.

**Comment by sds100** [comment]
> Still happening on 2.3.1. The app can't seem to replicate Android's native notification/quick settings fingerprint gesture behaviour, so it'd be pretty nice to be able to assign things to the left and right swipes without blocking the normal up and down behaviour.

This isn't possible unfortunately because Android doesn't allow it.

**Comment by lilithium-hydride** [comment]
> > Still happening on 2.3.1. The app can't seem to replicate Android's native notification/quick settings fingerprint gesture behaviour, so it'd be pretty nice to be able to assign things to the left and right swipes without blocking the normal up and down behaviour.
> 
> This isn't possible unfortunately because Android doesn't allow it.

Ah alright, my bad

**Comment by sds100** [comment]
@GL513 this still an issue? want to close old bug issues

**Comment by GL513** [comment]
Yeah, i was just thinking of this... Ill go ahead and close it for now.
