### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by sds100** [keymapperorg/KeyMapper#748]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] #1040
- [x] target API 31
- [x] update all libraries
- [x] Use jetpack splash screen library https://dev.to/tkuenneth/a-peek-inside-jetpack-core-splashscreen-odo
- [x] Test if notification trampoline works
- [x] Material You https://stackoverflow.com/questions/69065334/how-to-use-new-material-you-colors-announced-for-android-12
- [x] Material You migration guide https://material.io/blog/migrating-material-3
- [x] exported for all components
- [x] closing status bar action doesn't work on Android 12
- [x] squash and merge
- [x] delete branch

**Comment by GL513** [comment]
The Material You will cover all colors given by the system right?
Such as UI elements like buttons, the background, and *maybe* corner radius, if its a thing?

**Comment by sds100** [comment]
yeah, i think there is only an API for colors. i'm just going to wait for the Material components library to update the look of the widgets

**Comment by sds100** [comment]
this is STILL open...
