### ISSUE TITLE
"Sticky" Buttons

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#754]
Buttons that are previously pressed down and then released are perceived as still down.
I am not sure when i pressed the key, and it got "stuck", but i went to press another button, and it triggered an action, which i had set to run when i press both buttons.
You might see in the logs that i pressed the button a few times, mostly because i was trying to see if this was a device fault, or if it would repeat itself.

Here is the bug report link

https://cdn.discordapp.com/attachments/836164219073331213/871482661514911774/key_mapper_report_20210801-135635.zip

If this shows up again, ill be sure to let you know, as this is the most strange bug ive encountered so far.

**Comment by sds100** [comment]
can you still reproduce this issue?

**Comment by GL513** [comment]
> can you still reproduce this issue?

I cant just reporoduce it, so if you close this it wont be a huge deal. 
I just cant be sure if its fixed or not.
Like i said, if this problem appears again ill let you know. 🍉

**Comment by sds100** [comment]
ill close this for now

**Comment by GL513** [comment]
Closing this for now...
