### ISSUE TITLE
Action to run termux (tasker) scripts

### ISSUE THREAD

**Issue by Generator** [keymapperorg/KeyMapper#782]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] see https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent
- [ ] squash and merge
- [ ] delete branch

## Description
Termux supports running scripts from third party apps with ```termux-tasker```, users can create scripts and run them with Tasker (or other similar apps), some scripts could be run as root or ```termux-api```, ruining then with a single key wold be more easy then install another third party app and then run the task shortcut.

In my case i have an Android TV box, trying to run a script created on termux, i needed to install Automate create a new task (flow), then on KeyMapper map a key to run the Automate task shortcut.  
Running the script directly from KeyMapper would be more practical. 

Other option is to run shell scripts directly from KeyMapper (with or without su), just doesn't have Termux environment. This is related to #661

**Comment by sds100** [comment]
Yeah, this is a useful feature. Can you send me to the termux documentation that describes how to use their API?

**Comment by Generator** [comment]
I was going to include the link on OP, but forgot it, here it is (think is this one)
https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent

**Comment by GL513** [comment]
Wait, sds, weren't you planning on implementing Tasker plugins? So, with that said, what if that was implemented instead of that, plus this, if that would ever happen?

**Comment by sds100** [comment]
I am happy to implement both. It is likely that they will never happen though because I'm very busy. It would be better to have Termux support built-in instead of having to relay through Tasker.

**Comment by GL513** [comment]
>It would be better to have Termux support built-in instead of having to relay through Tasker.
You dont need to have tasker to use the tasker plugins. If you want, you can look at Llamalab's Automate app. they have tasker plugins, but i never had the tasker app, yet i still used the plugins.

**Comment by sds100** [comment]
oh right, interesting. Is there a common interface for all tasker plugins? #454 was about making a Key Mapper tasker plugin i think.

**Comment by GL513** [comment]
> oh right, interesting. Is there a common interface for all tasker plugins? #454 was about making a Key Mapper tasker plugin i think.

the interfaces are actually built into the app that has a plugin, which means a new sub-ui for keymapper :)

https://tasker.joaoapps.com/plugins-intro.html

**Comment by sds100** [comment]
So it is possible for me to add a single screen that means _any_ Tasker plugin can be used as an action?

**Comment by sds100** [comment]
I don't think #454  is required anymore since I've added a way to use Intents to launch Key Mapper actions. I will close it.

**Comment by GL513** [comment]
well, as i know it there are three kinds of plugins. Action conditions, State conditions, and Event conditions. I think you would want to use action conditions, but im not sure.
Plus, any users, if they wanted to, they could route the shortcut option through external apps, but then again, thats tricky if you dont know where to go.

here this page
https://tasker.joaoapps.com/pluginslibrary.html

**Comment by proItheus** [comment]
According to https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent ,a termux command can also be excuted by a simple intent as long as the app has the "com.termux.permission.RUN_COMMAND" permission. Just need to add this permission to the manifest, and you can excute termux script using the existing "intent" action.

**Comment by sds100** [comment]
Oh nice, I will add that and mention it in the website

**Comment by sds100** [comment]
I've implemented #928 . This will come in 2.4.0 Beta 2

**Comment by sds100** [comment]
I think using the Intent action is good enough instead of a complicated UI. Termux users are pro users so intents shouldn't too much to ask 😉

**Comment by sudomain** [comment]
@Generator Hello, I think I've found the same bug when saving a string array- Am I correct in saying it just doesn't get saved? Did you end up opening an issue for it?
