### ISSUE TITLE
Key mapper keyboard not showing

### ISSUE THREAD

**Issue by Zerobeliever32** [keymapperorg/KeyMapper#799]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
You can't perform any actions from key mapper because you can't switch to the key mapper keyboard

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here.](https://sds100.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**
![Screenshot_٢٠٢١١٠١٠-١٣٥٨٤٨](https://user-images.githubusercontent.com/92254269/136693534-b59e1a78-5016-407c-9b7b-16b702c34015.png)

![Screenshot_٢٠٢١١٠١٠-١٤٠٠١٩](https://user-images.githubusercontent.com/92254269/136693544-0ca5d830-a06c-4511-bc6a-daebc311669b.png)

**Smartphone (please complete the following information):**
 - Device: [Tecno Spark 6 Go]
 - Android version: [Android 10]

**Additional context**
d

**Comment by GL513** [comment]
This appears to be a device issue. The application must be the same locale as the system by default or something.
https://howto-android.com/how-to-change-language-on-tecno-spark-4/

**Comment by sds100** [comment]
@Zerobeliever32 does this explain the issue?

**Comment by jstetten** [comment]
The Key Mapper keyboard never appeared for me either, even after being enabled in input selections, so I've never been able to use this function. This is on a Samsung Galaxy S9 with only one locale, en-US.

**Comment by sds100** [comment]
Interesting... What if you install an old version (2.2.0) from the github releases?

**Comment by sds100** [comment]
Try to find a version that doesn't have this issue

**Comment by Zerobeliever32** [comment]
Yeah i actually did that and it's working perfectly fine, thanks

**Comment by sds100** [comment]
It is working in 2.2.0 but not in 2.3.0? Can you reproduce this by upgrading to 2.3.0?

**Comment by sds100** [comment]
Still reproducible? @Zerobeliever32

**Comment by sds100** [comment]
No response
