### ISSUE TITLE
Name mappings

### ISSUE THREAD

**Issue by mizzunet** [keymapperorg/KeyMapper#825]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

I have ten mappings, it often feels hard to find one to modify or do something on it. So, I wish Key Mapper could name these mappings, as they would be sorted, finding is easier than before.

Thank you ;)

**Comment by sds100** [comment]
Hi! There is already an issue for this called #701 ;)
