### ISSUE TITLE
Disable android physical keyboard system shortcuts

### ISSUE THREAD

**Issue by untoreh** [keymapperorg/KeyMapper#860]
I haven't found a way to disable the default android shortcuts that popup when pressing `ALT+/`.
I created a keyboard mapping for a shortcut with the `system -> do nothing` option, which successfully disabled the system action. But the combo is not registered on the app which needs it (a remote desktop client). 
Maybe a system option to forward the key combination to the current foreground app would work? I don't know how keyboard events are broadcasted across android applications...

**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Comment by sds100** [comment]
If this something done by the system then it looks like the system isn't forwarding the key events at all to _applications_ so Key Mapper's accessibility service also won't be able to detect it. Is this the case?
