### ISSUE TITLE
D-Pad, sticks, and triggers don't get picked up by Record Trigger

### ISSUE THREAD

**Issue by zulc22** [keymapperorg/KeyMapper#886]
The face buttons on my wireless XBOX controller work fine, but nothing else is picked up. When I try to press the analog stick or D-Pad directions it just moves the UI element focus.

**Comment by sds100** [comment]
Hi, this is a known issue with how Android sends key events to accessibility services. You can see my description of how to work around this here https://github.com/keymapperorg/KeyMapper/issues/199
