### ISSUE TITLE
Update website button (leads to 404 currently)

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#894]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] squash and merge
- [x] delete branch

"Website" button in about section is outdated

**Screenshots**
![Screenshot_20220206-061729_Chrome Canary.jpg](https://user-images.githubusercontent.com/83085846/152678438-4b45ba00-a3b8-44a6-b170-6424f236617c.jpg)

**Comment by sds100** [comment]
fixed
