### ISSUE TITLE
Change https to http in bottom bar discord button

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#901]
Discord button on bottom bar in guide is set to url https:// and not http://.
Ive notticed that this seems to hang my browser from doing anything.
The hyperlink needs to be set to http://
![Screenshot_20220206-150345_Chrome Canary.jpg](https://user-images.githubusercontent.com/83085846/152699285-f8d76031-7212-4fcb-9f03-d9fcc7aa9710.jpg)

**Comment by GL513** [comment]
Is there any chance you can add the unbuilt docs to another folder or make another repo for it @sds100

**Comment by sds100** [comment]
What do you mean by "unbuilt docs"?

**Comment by GL513** [comment]
> What do you mean by "unbuilt docs"?

Youknow when you do mkdocs build? Just put the " unbuilt" docs somewhere

**Comment by sds100** [comment]
There shouldn't be a need to. The point is that it is fully automated from the source code.

**Comment by sds100** [comment]
fixed
