### ISSUE TITLE
Add keymapper keyboard links to docs and app

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#902]
Add hyperlinks for Hackers keyboard and leanback keyboard in docs in keymapper keyboard section, and somewhere in the app (links to github releases)

**Comment by sds100** [comment]
You want to work on this?

**Comment by sds100** [comment]
I'm only adding it to the website for now because I don't really support or maintain them and adding a UI in the app is too much work for that.

**Comment by sds100** [comment]
implemented
