### ISSUE TITLE
The accessibility of my keymapper keeps crashing even i restart it many times and theres no apps that kills the accessibility acces of keymapper

### ISSUE THREAD

**Issue by Nixitys** [keymapperorg/KeyMapper#907]
My keymapper keeps crashing even i restart the accessibility many times but it didnt work i search on youtube how to fix it, but it didn't help
![Screenshot_2022-02-08-20-25-11-17](https://user-images.githubusercontent.com/99260296/152988451-6761eeda-98dc-497a-a23f-a4584ca358ca.png)

**Comment by sds100** [comment]
can you send me a bug report by following this guide https://docs.keymapper.club/report-issues/

**Comment by sds100** [comment]
post it here

**Comment by sds100** [comment]
stale
