### ISSUE TITLE
[Update] fix 2.4.0 material colors

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#908]

**Comment by sds100** [comment]
implemented

**Comment by sds100** [comment]
It looked completely different on another device, maybe i was being stupid and testing on Android 12. This is the theme for older than Android 12.

**Comment by GL513** [comment]
> > If you want you can play around with the colors here https://material-foundation.github.io/material-theme-builder/#/custom
> 
> 
> 
> Literally just stuck with RGBW for the default color slots and i think it looks pretty good.

And a quick green/blue invert
![Screenshot_20220210-152246_Chrome.jpg](https://user-images.githubusercontent.com/83085846/153490339-91f2970d-bb4c-478e-b93c-362782e97107.jpg)

**Comment by sds100** [comment]
![Screenshot_20220210-212311_Key_Mapper_Debug](https://user-images.githubusercontent.com/16245954/153490449-4d4a806b-0b52-4879-8e7f-13d44a6843cc.png)

what do you think about this green when it is in dark mode?

**Comment by sds100** [comment]
![Screenshot_20220210-212538_Key_Mapper_Debug](https://user-images.githubusercontent.com/16245954/153490654-2a182b68-b5f8-4401-9d41-7f0d24e9cb1b.png)

i actually quite like the blue from before. ill try that RGB palette

**Comment by sds100** [comment]
I think for light mode I will go with the blue as primary, red as secondary and green as tertiary. The red as primary doesn't work well.

**Comment by sds100** [comment]
crusty dark red 😂

**Comment by sds100** [comment]
![Screenshot_20220210-213610_Key_Mapper_Debug](https://user-images.githubusercontent.com/16245954/153492308-6c15b397-a5c3-4a1d-966f-29ba5d0b80a7.png)
![Screenshot_20220210-213619_Key_Mapper_Debug](https://user-images.githubusercontent.com/16245954/153492309-a604faf0-abc5-4801-9f3a-aac60efaec40.png)

**Comment by GL513** [comment]
![Screenshot_20220210-154630_Key Mapper CI.jpg](https://user-images.githubusercontent.com/83085846/153493699-e6b27f26-2e2d-41c9-973c-435355afb999.jpg)

First thing i saw was the weird contrast. It doesnt quite match with the rest

**Comment by GL513** [comment]
I think sticking with a super low saturated color, or no saturation would be best.

**Comment by sds100** [comment]
![Screenshot_20220210-214900_Key_Mapper_Debug](https://user-images.githubusercontent.com/16245954/153494059-58bba5c4-7e4b-4dd3-afb1-ebb8235dd638.png)
![Screenshot_20220210-214909_Key_Mapper_Debug](https://user-images.githubusercontent.com/16245954/153494061-bcb1890e-81b8-462f-bdaa-1898d45c4e84.png)

what about sticking to the red/blue in the dark theme as well?

**Comment by sds100** [comment]
Green is kind of shrek coloured

**Comment by GL513** [comment]
Yeah red and blue looks cool. If you pushed an update, i dont thinks its gotten to the discord yet

**Comment by sds100** [comment]
Okay, those colors it is then!

**Comment by GL513** [comment]
I was wondering if this was intentional. Im not saying it looks good or bad, but the delay box looks like it could be changed to a different color ![Screenshot_20220210-163334_Key Mapper CI.jpg](https://user-images.githubusercontent.com/83085846/153500341-c0ff49e5-bb91-461e-b714-2a2d803bca99.jpg)

**Comment by sds100** [comment]
fixed
