### ISSUE TITLE
[Update] Color consistency

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#909]
![Screenshot_20220209-180210_Key Mapper CI.jpg](https://user-images.githubusercontent.com/83085846/153305276-8a51c5db-e6b4-456a-bad6-09ba049834cc.jpg)![Screenshot_20220209-180204_Key Mapper CI.jpg](https://user-images.githubusercontent.com/83085846/153305286-5273164e-8a54-47e5-9283-6839f195bdb7.jpg)
Arrow in other menus (bottom left) doesnt appear to be the same color as in the "home" screen.

**Comment by sds100** [comment]
Good observation

**Comment by GL513** [comment]
> Good observation

I would apprciate it if you could update my image as well, but you dont really have to if its not an immediate need. If desired, i have the svg too.

https://media.discordapp.net/attachments/720595239831863307/939851374458449930/GL5132xx_2.png

**Comment by sds100** [comment]
You can do it ;) just need to replace a file in app/src/res/drawables

**Comment by sds100** [comment]
Or just search for a file name with gl513 and see what file it is.

**Comment by sds100** [comment]
fixed
