### ISSUE TITLE
[Update] Leave without saving fix

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#910]
![Screenshot_20220209-180141_Key Mapper CI.jpg](https://user-images.githubusercontent.com/83085846/153305491-16cd0b4d-2808-4ef3-a883-5e055bbe661e.jpg)

Add more padding to warning text top (Too little padding makes it look a tiny bit janky, no offense).

**Comment by sds100** [comment]
I am _supposed_ to add a title to dialogs, which is why the material component's styling looks weird now 😄.

**Comment by sds100** [comment]
fixed
