### ISSUE TITLE
Crashes on action edit

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#914]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
App crashes when going into a block, and tapping the edit button on the right of an action.

**To Reproduce**
Edit actions in a block

Upload a backup of your keymaps.
https://cdn.discordapp.com/attachments/836164219073331213/941444389564207145/0key_mapper_report_20220210-162050.zip

**Expected behavior**
Editing should edit, not crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: samsung galaxy a51
 - Android version: 11

**Additional context**

**Comment by sds100** [comment]
good spot

**Comment by GL513** [comment]
Am i wearing you out? Lol

**Comment by sds100** [comment]
fixed
