### ISSUE TITLE
Text overlays other areas before they can get out of the way

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#915]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

https://user-images.githubusercontent.com/83085846/153500593-393efeaa-ebdd-4a74-9ed7-6370c296842f.mp4

In constraints

**Comment by sds100** [comment]
so many bugs to work on... 😂 I need you to learn Android development as well! If something is a bug, always add it to the github project of the next release

**Comment by sds100** [comment]
is the issue that the "show an on-screen message" and "vibrate" options are covered when you check it?

**Comment by GL513** [comment]
> is the issue that the "show an on-screen message" and "vibrate" options are covered when you check it?

Yeah, if you notice, the vibrate elements fade in smoothly, while the external triggers just cut in.

**Comment by sds100** [comment]
> When you delete triggers and actions it cuts out as well, is this intentional?

can you show me? Maybe slow down your device's animations in Developer Options to see it better. All of the UI stuff and especially animations isn't really done by me. Its done by the libraries that make the UI components. Doing this stuff is a PITA to do yourself 😄

**Comment by GL513** [comment]
https://user-images.githubusercontent.com/83085846/153662940-da8acf4c-2b7c-48c7-aeb8-6d1682205cc7.mp4

**Comment by sds100** [comment]
ohh, i see what you mean now

**Comment by sds100** [comment]
There isn't a nice way to solve it. Fixing animations like this on Android is really annoying and a maintenance issue. I will forget to do it in other places and its just more work. I appreciate that attention to detail like this is important but I need to work on features 😄
