### ISSUE TITLE
Fix log copy button

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#920]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

   ![Screenshot_20220211-134908_Key Mapper CI.jpg](https://user-images.githubusercontent.com/83085846/153651732-f364d803-3309-469e-9fc1-c0d9139c2926.jpg)

I think its just a missing color variable. Its black or close to it in light mode, and its like that in dark mode as well, being nearly invisible, but its not supposed to be.

**Comment by GL513** [comment]
sds, maybe you should show me how to do this one lol

**Comment by sds100** [comment]
haha, just look at the differences between that button and the others. look at the drawables for it. this took 30 secs so ive fixed it already ;)
