### ISSUE TITLE
Multiple touchscreen at the same time

### ISSUE THREAD

**Issue by awddawawd** [keymapperorg/KeyMapper#922]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
I don't know if it's a bug or if it's just not added, but when i try to trigger two touch screen at the same time using a bluetooth keyboard, the first one stops and the second one work fine.

**To Reproduce**
create a toggle action that triggers a touchscreen, create a push until release action that do the same.

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by sds100** [comment]
Hi, this isn't a bug it is is a limitation of Android. There is no way to fix this. Android only allows accessibility services to tap the screen in one place a time. 🙂
