### ISSUE TITLE
Can order be ignored currently? ctrl+alt+1 = alt+ctrl+1?

### ISSUE THREAD

**Issue by gzyguo** [keymapperorg/KeyMapper#940]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

Currently I have to create pairs of triggers for this reason, it is the modifier keys to keep their order in mind in practice is a burden for me, hope there is a switch to turn this discrimination off.

**Comment by sds100** [comment]
Duplicate of #591
