### ISSUE TITLE
Scancode is not reported correctly

### ISSUE THREAD

**Issue by albfan** [keymapperorg/KeyMapper#941]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
Scan code reported as zero

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**
This is an otg USB gsmepad connected to phone.

Button a is reported as Button_c. Remapping is not working.

The only difference I found with game tester is the scan code

**Screenshots**
![Screenshot_2022-03-01-21-04-26-416_io github sds100 keymapper](https://user-images.githubusercontent.com/220968/156241688-16a4ff0b-e319-452b-bfcf-bd803a733a47.jpg)

**Smartphone (please complete the following information):**
 - Device: redmi note 9
 - Android version: 11

**Additional context**
Scan conde is not reported so apps cannot detect the new key

Here a screencast: first press Button Y that exposes Button_a with scancode 304, then Button A with remapping reporting almost Button_a but with scancode 0

https://user-images.githubusercontent.com/220968/156241152-ebf49060-570b-4556-9a19-d1dcb16e2f51.mp4

**Comment by sds100** [comment]
Hi, I think this is a known issue, would #761 fix this?

**Comment by sds100** [comment]
Hi @albfan, have you opened the project in Android studio? You should just be able to clone it and then press the Run button in Android Studio.

**Comment by albfan** [comment]
For keymapperkeyboard that was It. Have to try again. Will report on another issue of so. I'm on Linux if that matters.

Is the scancode read in the end?

**Comment by sds100** [comment]
I use Linux as well so it should be fine - linux is easier than windows to get it a dev environment set up 😄. Right now Key Mapper doesn't take into account the scan code at all when creating and detecting triggers.

**Comment by sds100** [comment]
@albfan can I close this and just leave #761 as a solution?

**Comment by albfan** [comment]
Sure
