### ISSUE TITLE
shizugu not usefull ,settings is not usefull

### ISSUE THREAD

**Issue by s6677** [keymapperorg/KeyMapper#945]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**
[
[key_mapper_report_20220305-090921.zip](https://github.com/keymapperorg/KeyMapper/files/8189390/key_mapper_report_20220305-090921.zip)
](url)

**Comment by s6677** [comment]
2.4.0 bug ,set key ,not usefull

**Comment by jambl3r** [comment]
Please explain the issue you are facing according to the template. A bug report without context isn't helpful on its own
