### ISSUE TITLE
Constraints>Bluetooth device is DISconnected changed to CONNECTED automatically everytime after save.

### ISSUE THREAD

**Issue by gzyguo** [keymapperorg/KeyMapper#946]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] squash and merge
- [x] delete branch

**Discord message link/email recipient**
6zyguo@gmail.com

**Describe the bug**
Constraint 'Bluetooth device is disconnected' change to 'Bluetooth device is connected' after save Key Event.

**To Reproduce**
Create Key Event
Add Constraint: Bluetooth device is disconnected
Select device
Save

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]
https://drive.google.com/file/d/1imq0wJNz6Wr5Omq5WoMkG2BHVoI11peV/view?usp=sharing

**Expected behavior**
Constraint 'Bluetooth device is disconnected' stick to 'Bluetooth device is disconnected' after save Key Event.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - Android version: Android 11

**Additional context**

**Comment by jambl3r** [comment]
Please explain the issue you are facing according to the template

**Comment by sds100** [comment]
I think this bug was fixed, can you install 2.4.0 Beta 1 from github releases and check

**Comment by sds100** [comment]
Can confirm it is not fixed

**Comment by sds100** [comment]
fixed
