### ISSUE TITLE
Add sms permission

### ISSUE THREAD

**Issue by Samuel-EA** [keymapperorg/KeyMapper#947]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
When trying to send sms using intent action it throws security error

**To Reproduce**
Add an action type intent and use ACTION_SENDTO fill Data field using smsto:PHONE_NUMBER and trigger action

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**
Be able to send sms via intent action when triggered

**Screenshots**

![Screenshot_2022-03-12-01-59-26-42_9c8362cc5290d10886fd53faced8c103.jpg](https://user-images.githubusercontent.com/54830775/158009790-80969021-4c2a-4701-a816-fa61f9384fe0.jpg)

**Smartphone (please complete the following information):**
 - Device: Realme 6
 - Android version: Android 11

**Additional context**
You can solve it adding messaging permission

**Comment by sds100** [comment]
Thanks for this report. Would this also be fixed by #727 ?
