### ISSUE TITLE
Unable to navigate app using TV remote

### ISSUE THREAD

**Issue by TrueCitrus** [keymapperorg/KeyMapper#954]
I cannot seem to navigate all areas of the app using my Android TV remote. It keeps skipping over the button when using the D pad on the remote. I am using a TiVo Stream 4K device running Android 9. How can I navigate to to the “Add action” button using my remote? Does this app require the use of a mouse?

**Comment by sds100** [comment]
Hi! This is a known issue and since the app doesn't officially support Android TV yet, I haven't invested the time to make this work. :) Please see #527
