### ISSUE TITLE
Bixby/Menu and Search button support with screen off

### ISSUE THREAD

**Issue by t184256** [keymapperorg/KeyMapper#955]
> These are the buttons which can be detected when the screen is off. Let the developer know about any buttons you would also like to be supported.
>
>    Volume Up
>    Volume Down
>    Headset button

My device (Samsung S10e) has that Bixby button, detectable as `Menu`. Could it be supported for remapping with the screen off?

**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] update documentation
- [ ] squash and merge
- [ ] delete branch

**Comment by sds100** [comment]
Hi, yeah it can be! The screen-off detection is _very janky_ though and only works if you are rooted. No guarantee that it will work well on your device.

**Comment by t184256** [comment]
Mine's rooted, so I'm not deterred =) I can test a build if you're willing to provide one.

**Comment by BlueStarZero** [comment]
My S9+ is rooted as well. Thanks so much for adding the Bixby button to this list. (No rush! I'll make do for now.) I'll also be happy to test a build, if you'd like.

**Comment by iFUCKINGHATEcomputers** [comment]
What about the Google Assistant button? To my untrained eyes it would appear to basically be the same thing. 

KeyMapper labels it as `Search` on my Moto G 5G,

**Comment by iFUCKINGHATEcomputers** [comment]
This thread seems to be the most relevant for me to ask - what about supporting the Google Assistant button when the screen is off? KeyMapper labels it as `Search` on my Moto G 5G.

**Comment by sds100** [comment]
@t184256 @BlueStarZero can you please try this apk :) [keymapper-2.5.0-alpha-debug.zip](https://github.com/keymapperorg/KeyMapper/files/8591606/keymapper-2.5.0-alpha-debug.zip)

**Comment by sds100** [comment]
> This thread seems to be the most relevant for me to ask - what about supporting the Google Assistant button when the screen is off? KeyMapper labels it as `Search` on my Moto G 5G.

I'll add this as well!

**Comment by sds100** [comment]
@iFUCKINGHATEcomputers can you try this apk for the search button :) [keymapper-2.5.0-alpha-debug.zip](https://github.com/keymapperorg/KeyMapper/files/8591695/keymapper-2.5.0-alpha-debug.zip)

**Comment by BlueStarZero** [comment]
> @t184256 @BlueStarZero can you please try this apk :) [keymapper-2.5.0-alpha-debug.zip](https://github.com/keymapperorg/KeyMapper/files/8591606/keymapper-2.5.0-alpha-debug.zip)
> 

Thanks for this alpha build, but i couldn't get the Bixby (Menu) button to work properly. Mappings seem to work fine when the screen is on, but not at all whenthe screen is off and phone is locked, even when I added in the "Screen is off" constraint and checked the "Detect when screen is off" checkbox. I wonder if @t184256  is having the same issue.

**Comment by t184256** [comment]
Didn't work, sadly. Volume down works fine with screen off, Menu button with same conf doesn't, nothing observed in the logs related to me pressing it.

**Comment by sds100** [comment]
> Didn't work, sadly. Volume down works fine with screen off, Menu button with same conf doesn't, nothing observed in the logs related to me pressing it.

Okay, can you two run the `adb getevent` command and press the Bixby button and show me the output?

**Comment by BlueStarZero** [comment]
Here's what my output looks like:

star2lte:/ $ getevent
add device 1: /dev/input/event3
  name:     "ssp_context"
add device 2: /dev/input/event8
  name:     "certify_hall"
add device 3: /dev/input/event2
  name:     "grip_sensor"
add device 4: /dev/input/event1
  name:     "sec_touchpad"
add device 5: /dev/input/event4
  name:     "hrm_sensor"
add device 6: /dev/input/event0
  name:     "sec_touchscreen"
add device 7: /dev/input/event6
  name:     "gpio_keys"
add device 8: /dev/input/event7
  name:     "hall"
add device 9: /dev/input/event5
  name:     "Headset"
Bixby button to play/pause media (screen on):
/dev/input/event6: 0001 02bf 00000001
/dev/input/event6: 0000 0000 00000000
/dev/input/event6: 0001 02bf 00000000
/dev/input/event6: 0000 0000 00000000
Power button to turn off screen and lock device:
/dev/input/event6: 0001 0074 00000001
/dev/input/event6: 0000 0000 00000000
/dev/input/event6: 0001 0074 00000000
/dev/input/event6: 0000 0000 00000000
Bixby button to play/pause media (screen off) [this does nothing]:
/dev/input/event6: 0001 02bf 00000001
/dev/input/event6: 0000 0000 00000000
/dev/input/event6: 0001 02bf 00000000
/dev/input/event6: 0000 0000 00000000

**Comment by sds100** [comment]
@BlueStarZero sorry, can you do `getevent -lq`

**Comment by BlueStarZero** [comment]
No problem. This looks more understandable:

star2lte:/ $ getevent -lq
Bixby button to play/pause media (screen on):
/dev/input/event6: EV_KEY       02bf                 DOWN
/dev/input/event6: EV_SYN       SYN_REPORT           00000000
/dev/input/event6: EV_KEY       02bf                 UP
/dev/input/event6: EV_SYN       SYN_REPORT           00000000
Power button to turn screen off & lock device:
/dev/input/event6: EV_KEY       KEY_POWER            DOWN
/dev/input/event6: EV_SYN       SYN_REPORT           00000000
/dev/input/event6: EV_KEY       KEY_POWER            UP
/dev/input/event6: EV_SYN       SYN_REPORT           00000000
Bixby button to play/pause media (screen off) [this does nothing]:
/dev/input/event6: EV_KEY       02bf                 DOWN
/dev/input/event6: EV_SYN       SYN_REPORT           00000000
/dev/input/event6: EV_KEY       02bf                 UP
/dev/input/event6: EV_SYN       SYN_REPORT           00000000

**Comment by sds100** [comment]
try this :) [keymapper-2.5.0-alpha-debug.zip](https://github.com/keymapperorg/KeyMapper/files/8592757/keymapper-2.5.0-alpha-debug.zip)

**Comment by BlueStarZero** [comment]
MAN, you work fast. I'll give this one a try!

**Comment by sds100** [comment]
> MAN, you work fast. I'll give this one a try!

Haha, this issue is just changing one line 😄

**Comment by t184256** [comment]
On the go, but that one seems to work in general with just a ~second window of not working immediately after I lock the screen.

**Comment by sds100** [comment]
> On the go, but that one seems to work in general with just a ~second window of not working immediately after I lock the screen.

Yeah, this is an issue with this method. It is _super_ janky. I'm not sure what I can do to improve it.

**Comment by t184256** [comment]
Well, it's infinitely more useful than a button that just does nothing when I operate my device from the pocket, so I'm happy.

**Comment by sds100** [comment]
> Well, it's infinitely more useful than a button that just does nothing when I operate my device from the pocket, so I'm happy.

Cool, I'll merge this request then

**Comment by sds100** [comment]
implemented

**Comment by BlueStarZero** [comment]
You did it! It seems to work now! Although, sometimes, I have to press the button when once before the map actually works.

But for now, it's working properly. I'll have to daily drive for a while to get a better feel of my maps. Thank you do much!

**Comment by iFUCKINGHATEcomputers** [comment]
Ayy the, `Search` button works!
