### ISSUE TITLE
Unable to record a trigger

### ISSUE THREAD

**Issue by Lakshmisai3137** [keymapperorg/KeyMapper#956]
![Screenshot_20220325-224005_Key Mapper](https://user-images.githubusercontent.com/102380134/160169890-cab47831-7cd0-449a-8558-1c77d1abff17.jpg)
It is stuck at 2 sec and that is why I am unable to create/record a new trigger.
Thank you

**Comment by sds100** [comment]
Hi, does it count down from 5? If so, then I have no idea why it would be doing that. Please fill in the issue template with all the necessary information.
