### ISSUE TITLE
"Set flags" of an Intent do not reflect current non-empty content of the input field

### ISSUE THREAD

**Issue by dumblob** [keymapperorg/KeyMapper#957]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] squash and merge
- [x] delete branch

**Discord message link/email recipient**
N/A

**Describe the bug**
In the "Action" tab under "Intent" there is a "Set flags" button and right above the button there is an integer input field. If this field is non-empty with a valid value, then clicking the button "Set flags" opens a list of all possible flags but none of the flags is selected.

**To Reproduce**
Create a new trigger, switch to "Action" and then to the "Intent" tab. Then click "Set flags", select e.g. the first two items from the pop-up list and confirm selection. Then click the "Set flags" button again and voila, the first two items are **not** selected.

~Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]~

**Expected behavior**
The pop-up list shall have selected items according to what the flag integer value represents.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung J5
 - Android version: Android 7
 - KeyMapper: 2.3.3 (yes, it's old - but that's the newest available in F-Droid)

**Additional context**
N/A

**Comment by sds100** [comment]
fixed
