### ISSUE TITLE
Mapping left and right stick

### ISSUE THREAD

**Issue by godzellax** [keymapperorg/KeyMapper#958]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

Is there any way to map buttons to left and right sticks actions i.e. 4 directions of both of them because I saw an app offer that option by mapping left stick to wasd and right stick to ijkl then you can map wasd and ijkl to any physical buttons
Thanks,

**Comment by sds100** [comment]
Hi, this is a highly requested feature but is a huge feature to implement, and I have very little time to work on the app. See #199 #180
