### ISSUE TITLE
Not work record 

### ISSUE THREAD

**Issue by Arsi2829** [keymapperorg/KeyMapper#975]
![Screenshot_۲۰۲۲۰۴۱۷-۱۷۱۲۰۰](https://user-images.githubusercontent.com/98885579/163714711-7c10a38e-df5f-47ae-8269-56b3396ace75.png)

![Screenshot_۲۰۲۲۰۴۱۷-۱۷۱۲۰۰](https://user-images.githubusercontent.com/98885579/163714698-db01a0dc-443d-4b7b-b48f-379a88d3931a.png)

 - Device: [Motorola one action]
 - Android version: [e.g. Android 11]
Please fix bug

**Comment by GL513** [comment]
Hello. Would you mind using keymapper to do a bug report? A screen recording might also be nice.

**Comment by jambl3r** [comment]
Closed as duplicate of https://github.com/keymapperorg/KeyMapper/issues/248
