### ISSUE TITLE
Release beta version on F-Droid

### ISSUE THREAD

**Issue by Generator** [keymapperorg/KeyMapper#976]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

## Description
Release beta versions on F-Droid (has non-recommended) for testing new features.
Otherwise users need to swap between F-Droid <-> Google Play (or GitHub) builds to test new features.

**Comment by sds100** [comment]
Oh cool, there is a way to have separate builds on F-droid?

**Comment by sds100** [comment]
Hmm, it looks like I'll have to manually create an issue to update the f-droid metadata every time a beta is released. I want to reduce the things I need to do to release an update - makes me less likely to hold off doing it ;). You can work on this if you want.

**Comment by sds100** [comment]
It seems like this has to be done manually and I would prefer to keep beta releases as opt-in. I will try to increase the release cadence to ensure people don't have to wait a long time for updates. :)
