### ISSUE TITLE
Backup not working on Android TV

### ISSUE THREAD

**Issue by aus10code** [keymapperorg/KeyMapper#978]
"You don't have an app that can do this" when clicking button "BACKUP EVERYTHING" as shown in the screenshot. 

Clicking button "RESTORE" works as you can see in the screenshot. I have 3 file explorers installed as shown in the restore screenshot.

# Backup doesn't work
![image](https://user-images.githubusercontent.com/62197117/165367714-f48239fb-794c-48ac-9a24-d2a8313572bf.png)
# Restore works
![image](https://user-images.githubusercontent.com/62197117/165367734-dfc526bd-e125-471f-b4f7-92693679b005.png)

# Device details
![image](https://user-images.githubusercontent.com/62197117/165367270-059a0467-d002-4505-9ac7-b5e0dd2762df.png)
![image](https://user-images.githubusercontent.com/62197117/165367343-5bda88c3-421f-43d2-8a86-a6bdaa06b633.png)

**Comment by aus10code** [comment]
I'm not sure if you have a device that can test this. I can help if given the produced apk file with the fix or if the build process is simple enough I can build from the branch myself.

**Comment by sds100** [comment]
> "You don't have an app that can do this" when clicking button "BACKUP EVERYTHING" as shown in the screenshot.
> 
> Clicking button "RESTORE" works as you can see in the screenshot. I have 3 file explorers installed as shown in the restore screenshot.
> # Backup doesn't work
> 
> ![image](https://user-images.githubusercontent.com/62197117/165367714-f48239fb-794c-48ac-9a24-d2a8313572bf.png)
> # Restore works
> 
> ![image](https://user-images.githubusercontent.com/62197117/165367734-dfc526bd-e125-471f-b4f7-92693679b005.png)
> # Device details
> 
> ![image](https://user-images.githubusercontent.com/62197117/165367270-059a0467-d002-4505-9ac7-b5e0dd2762df.png) ![image](https://user-images.githubusercontent.com/62197117/165367343-5bda88c3-421f-43d2-8a86-a6bdaa06b633.png)

This seems to be an error message by your operating system. When I run it on my Android TV emulator it just crashes because it doesn't have an app installed that act as a file picker (this is another bug to fix). Can you install [Mixplorer](https://forum.xda-developers.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691). I think this has a file picker

**Comment by aus10code** [comment]
That did the trick. Thanks for hopping on this bug so quickly and doing the ground work to find a working app for me. I really appreciate it!!!

![image](https://user-images.githubusercontent.com/62197117/166069820-f5a122b8-3271-447a-bb1c-d37a4917be5d.png)

**Comment by sds100** [comment]
Great that its fixed!
