### ISSUE TITLE
Support for Android 10 (Not working for my Lenovo) I can't update anymore, it says this isn't supported on play store.

### ISSUE THREAD

**Issue by ItsCyberBush** [keymapperorg/KeyMapper#979]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Comment by sds100** [comment]
Hi, which version of the app do you have installed? Are you enrolled in the beta program for the app?

**Comment by ItsCyberBush** [comment]
No, I am unable to install keymapper from playstore so not sure what version is in playstore... I found out I can install keymapper debug from this GitHub site though.

**Comment by GL513** [comment]
> No, I am unable to install keymapper from playstore so not sure what version is in playstore... I found out I can install keymapper debug from this GitHub site though.

Gooogle play has been slowly removing the current version  from the "about this app" section, but just in case, please check there.

**Comment by sds100** [comment]
> No, I am unable to install keymapper from playstore so not sure what version is in playstore... I found out I can install keymapper debug from this GitHub site though.

I think I fixed this with 2.4.0 so can you try to enroll in the beta program? It should allow you to install it.

**Comment by sds100** [comment]
No response and I think this is fixed.
