### ISSUE TITLE
Auto-export logs

### ISSUE THREAD

**Issue by GL513** [keymapperorg/KeyMapper#980]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

When the app crashes and you are locked out like in #965, its handy to be able to access the logs even if you cant maunally create a bug report.
This would be a toggle below the "view log" button, and when the app has any sort of crash, it will export the log and show a toast.
I would imagine keeping every single log isnt needed, so i think keeping the last 7 logs is an okay number.

**Comment by sds100** [comment]
Unfortunately apps can't write logs to public storage without the user going through the steps of granting the permission so it is actually quite complicated to implement. I'll see if I can make the app show a dialog allowing you to "share" the file before it _finishes_ crashing ;)

**Comment by sds100** [comment]
I'm not going to do this. Need to get the requests down...
