### ISSUE TITLE
Constraint for charging / on battery power

### ISSUE THREAD

**Issue by t184256** [keymapperorg/KeyMapper#989]
I found myself wishing for a "wired ADB debugging connected" constraint,
but that's rather niche,
and I think I could readily approximate it with a more commonplace "charging" constraint.

**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] update documentation
- [x] squash and merge
- [x] delete branch

**Comment by GL513** [comment]
Hello. I think it would be easy to get the value of the ADB debugging, but wether its wired or wireless might be a challange.
All that would need to happen for ADB *in general* is reading a secure setting.
If you wanted to, you could use keymapper to run a shortcut to Tasker or AutoMate and have *that* application do its own "constraint".

I thought we *did* have a charging constraint but it appears not...
Im not sure exactly how that works, but I do know that even if these do get done, it might be a while before its finished and bug free.

Thanks for the feedback :)

**Comment by sds100** [comment]
implemented
