### ISSUE TITLE
One action cancels other held tap screen action.

### ISSUE THREAD

**Issue by MikeSteinar** [keymapperorg/KeyMapper#998]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Email recipient**
mikesteinar@gmail.com

**Describe the bug**
Trying to use Key Mapper for mobile game. Problem is when i push shot button the character/vehicle stop moving. Using tap screen trigger causes the other held trigger to stop.

**Expected behavior**
Using tapscreen action has not affect the performance of another held tap screen Action. So when i shooting character/vehicle has keep moving while i use appropriate action.

**Screenshots**

**Smartphone:**
 - Smsung A22 5G
 - Android 11

**Additional context**
Game: WOT Blitz

**Comment by sds100** [comment]
Hi, this is a known restriction in Android and so it is impossible for me to fix this. 🙂
