### ISSUE TITLE
delay opening app when performing open app action from the home screen

### ISSUE THREAD

**Issue by xi7** [keymapperorg/KeyMapper#999]
Solution: Use PendingIntent

always when press home button, need wait long delay ~10s until show the app again after press the key mapper. (any app )

android 5.1 , tested with 3 devices different  (it not happen with remapper app)

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/168441680-f3321c10-c49c-43f0-a7ac-c723d62fd968.mp4

keymapper vs remapper

**Comment by sds100** [comment]
Interesting, can you send me a link to this other app in the play store?

**Comment by xi7** [comment]
https://play.google.com/store/apps/details?id=com.sumyapplications.button.remapper

**Comment by GL513** [comment]
Hey, that's the one I used to use before I found keymapper.
Looks like there has been a lot of improvements. I thought the app was stale...
I do know that the remapper app does tend to be finicky though, even if battery optimization is turned off.

**Comment by xi7** [comment]
but i need the intent mod with extra boolean option, the remapper cant do it.

need the keymapper fix the delay bug :)

**Comment by GL513** [comment]
> but i need the intent mod with extra boolean option, the remapper cant do it.
> 
> need the keymapper fix the delay bug :)

If you want to get technical, you could export your keymaps, edit the file, find the keymap you are looking for, and see if modifing the time from the .json file helps for now.

**Comment by xi7** [comment]
![Screenshot_2022-05-14-20-22-48](https://user-images.githubusercontent.com/67331785/168451152-ce249e88-6fe5-4476-961a-314d63c58a11.png)

this is my file backup data.json , all delay looks good there and still slow after press home.

**Comment by xi7** [comment]
v2.4.1 still same problem delay, after press home.

**Comment by sds100** [comment]
Can you go back in older key mapper versions (start with 1.x) and see if it also happens?

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/172618012-586ff930-54a6-4bb8-a56f-310ad56b6350.mp4

**Comment by sds100** [comment]
@xi7 I'm confused how you are reproducing this. What key maps do you have? Can you post the bug report by following this guide https://docs.keymapper.club/report-issues/

**Comment by xi7** [comment]
[key_mapper_report_20220608-221308.zip](https://github.com/keymapperorg/KeyMapper/files/8869212/key_mapper_report_20220608-221308.zip)

**Comment by sds100** [comment]
I can reproduce it, will investigate...

**Comment by xi7** [comment]
after install v 2.4.3 still same problem here, big delay

**Comment by sds100** [comment]
Noo

**Comment by xi7** [comment]
was solved the problem with *launch app* but i use *launch app shortcut * and the problem persist

**Comment by sds100** [comment]
Oh, okay. I didn't think of that. Will fix.

**Comment by xi7** [comment]
no have paypal ?

**Comment by sds100** [comment]
I did but then they accused me of being fraudulent or something and were asking for all my security and identification information just to "maybe" fix the problem. So I just stopped using it. 😄 Haven't had this issue with other platforms.

**Comment by sds100** [comment]
Thank you 😀! Now Stripe also want my ID to verify. Seems to be less intrusive than PayPal though. 😄
